### ISSUE TITLE
Legacy Anna: climate entity missing

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/plugwise-beta#49] opened 2020-04-28 17:27 UTC
Hi Gents I am currently running 0.2.0 on HA on version 219.
Got everything running. But I dont get the climate entity?

I do get 2 entities called "Anna" and "Smile_Anna" but they only contain information. ( i.e. sensors )

![image](https://user-images.githubusercontent.com/56043947/80515154-c8bf7b00-8981-11ea-97b0-46779f10c971.png)

_Originally posted by @AussiSG in https://github.com/laetificat/haanna/issues/19#issuecomment-620732495_

**Comment by bouwew** [comment] 2020-04-28 17:29
@AussiSG, please respond in this topic.

**Comment by bouwew** [comment] 2020-04-28 17:50
@AussiSG, do you see any Error related to plugwise-beta in Developer Tools --> Logs?

If not, can you please activate debug-logging for plugwise-beta?:
```
logger:
  default: warn
  logs:
    custom_components.plugwise-beta: debug
```
And restart HA after this change?

After the restart, at Developer Tools --> Logs, load the FULL HA LOG.
There should be many plugwise-beta related messages, can you please show them to us?

**Comment by AussiSG** [comment] 2020-04-28 18:10
Yes, I have update to the beta version of HA (Home Assistant 0.109.0b4).

Here is a full copy of the HA log:

https://pastebin.com/nMLqeHpX

Dont mind the error of the serial / usb thingy still struggling with hehe

**Comment by bouwew** [comment] 2020-04-28 18:16
Thanks! I can see what went wrong: `Single master thermostat = None`.
Should be `True` in your system as you have a legacy Anna, correct?

**Comment by AussiSG** [comment] 2020-04-28 18:17
Correct

**Comment by CoMPaTech** [comment] 2020-04-28 19:12
(possible) Code improvements underway

**Comment by CoMPaTech** [comment] 2020-04-28 19:42
We're deliberating, my PR is an improvement but probably won't fix it. Can you check http://192.168.x.y/core/locations.xml on your Smile? It's probably pretty empty like (this one)[https://github.com/plugwise/Plugwise-Smile/blob/master/tests/legacy_anna/core.locations.xml]

The second question is what firmware are you running according to the interface? Is this 1.8 or a 3.x or 4.x?

We're readying the PR anyway and will be dropping a pre-release here - if you use HACS make sure you tick the dots right top of the integration and enable 'beta'.

**Comment by CoMPaTech** [comment] 2020-04-28 19:56
@AussiSG besides the above request (mainly which firmware you are on according to you app or Smile itself) - 
`0.2.1a1` should be visible from HACS - please leave your logging set to debug, below `Gateway is <some long alphanumeric string>` there should be some relevant information. 

The debug logging might be stating 1.8.0, 3.3.9 or something but we're really looking for what your app tells you.

**Comment by AussiSG** [comment] 2020-04-29 05:16
Goodmorning. 

Anna is currently running the following software/hardware, found on the internal website
![image](https://user-images.githubusercontent.com/56043947/80562294-9ea0a400-89e7-11ea-8de8-5eb6a6d84e59.png)

Complete log after restart HA:
https://pastebin.com/svaEYDUv

And 

Here is snip of my /locations.xml
[image](https://user-images.githubusercontent.com/56043947/80562839-3a7edf80-89e9-11ea-87b1-7ab2c3410323.png)
Looks like it isnt there?

**Comment by CoMPaTech** [comment] 2020-04-29 05:38
My bad, its http://w.x.y.z/core/locations (without the xml - but it still should be empty). We'll check your pastebin, it still says it didn't find a master thermostat even though we already should have 1.8 fw working.

**Comment by AussiSG** [comment] 2020-04-29 05:43
![image](https://user-images.githubusercontent.com/56043947/80564066-19b88900-89ed-11ea-916e-926f0ce8699f.png)
That has some more content indeed.

Yea thats wat I spotted aswell in the logs

**Comment by CoMPaTech** [comment] 2020-04-29 05:50
Well this explains a lot (now) ... the assumption on test input was 1.8 didn't have locations, so if it has some of the logic is now bypassed. Seeing your output I assume (new one) that the other 1.8 didn't have outdoor_temp monitored and hence got no location.

Tnx, 'll get back to you

**Comment by CoMPaTech** [comment] 2020-04-29 06:17
`0.2.1a2` should be ready to install

**Comment by AussiSG** [comment] 2020-04-29 06:18
Gonna try it out.
Altho the outdoor temp sensor dont make sense... It always states that it's 21.01 degree outside.....

**Comment by AussiSG** [comment] 2020-04-29 06:28
This is more like it 👍 Great sorting guys.
Thanks for the support of the extreme legacy anna hehe

![image](https://user-images.githubusercontent.com/56043947/80566463-5d15f600-89f3-11ea-812b-fccd5a90a06d.png)

**Comment by CoMPaTech** [comment] 2020-04-29 06:36
Great to see it working - in retro, maybe the 1.8 indeed shouldn't have locations but yours just got it anyway ... Leaving the issue open so @bouwew is also informed

**Comment by bouwew** [comment] 2020-04-29 06:38
@AussiSG Can you please post the log-output of the last HA start, with 0.2.1a2 loaded?

**Comment by AussiSG** [comment] 2020-04-29 06:38
Yea I have been messing with different Anna gateways because of getting a busted one from Marketplace..... 

But : after deleting the integrations and looking it back up the additional sensor seem to be coming in 👍

**Comment by bouwew** [comment] 2020-04-29 06:42
Ah Ok, remnant devices... Indeed then better to delete the integration and add it again. What do you see now? Can you post the Integration-screen showing the 2 main devices? And then per device the attached entities? So we can double-check everything is OK?

**Comment by AussiSG** [comment] 2020-04-29 06:53
Sure thing. Here are the devices:
![image](https://user-images.githubusercontent.com/56043947/80568111-b03d7800-89f6-11ea-81d2-298d687466d8.png)

And here some detailed info of the added entities:
![image](https://user-images.githubusercontent.com/56043947/80568202-dcf18f80-89f6-11ea-8e07-115991091d4e.png)
![image](https://user-images.githubusercontent.com/56043947/80568218-e844bb00-89f6-11ea-99d8-05933008a0a9.png)

**Comment by AussiSG** [comment] 2020-04-29 06:58
Having a closer look on the entities.
I see the preset_mode state "null" is back. I think we had this sorted in the version 0.1.18

**Comment by bouwew** [comment] 2020-04-29 07:04
Please post the log-output of the last start showing the plugwise-beta debug messages, there should be a clue for us why it's null.

**Comment by AussiSG** [comment] 2020-04-29 07:13
Yes a fresh one after a fresh restart:

https://pastebin.com/7ZpE250M

**Comment by bouwew** [comment] 2020-04-29 07:26
I see in your output: active-preset : None, this is causing the null-results.

It would help us enormously if you could capture the XML-data from your Anna/Smile, see here: https://github.com/plugwise/Plugwise-Smile/tree/master/tests how to do it, scroll down to see the README-text.

**Comment by AussiSG** [comment] 2020-04-29 08:26
Hmm I have picked up all the request XML files. 
But I cant find any of the mentioned variables that need to be replaced due to privacy.
I hope I am doing it in the right way?

**Comment by AussiSG** [comment] 2020-04-29 09:35
Here is the zip file with the data. 
I hope its good for you. I didnt find any privacy related stuff in it strangely enough
[Anna.zip](https://github.com/plugwise/plugwise-beta/files/4550836/Anna.zip)

**Comment by CoMPaTech** [comment] 2020-04-29 10:00
I don't see any details in there, I think the 1.8 fw doesn't have anything like smile-id's in there. Added your files to our testsetup, but will continue tonight on the auxiliary stuff unless @bouwew already want to tinker with it. The testfiles have been added to a PR in the module repo, tnx!

**Comment by bouwew** [comment] 2020-04-29 17:43
@AussiSG Can you please test v0.2.1a3? This update should solve the preset_mode showing "null". Instead it should show "none" when no preset is selected. Can you also activate a preset to see if that works too?

**Comment by CoMPaTech** [comment] 2020-04-30 13:28
💯

**Comment by AussiSG** [comment] 2020-04-30 13:36
Thanks for the superb work guys to also make this possible on my 'old' Anna  👍 👍

**Comment by bouwew** [comment] 2020-04-30 13:43
@AussiSG Can you disable the preset? Then preset_mode should shown "none" instead of null.
When you report this result back, then the final issue is fixed :)

**Comment by AussiSG** [comment] 2020-04-30 13:45
Si :D
![image](https://user-images.githubusercontent.com/56043947/80717769-8b7df900-8af9-11ea-89c9-959fa0dd6e46.png)

**Comment by bouwew** [comment] 2020-04-30 13:46
Nice! Thanks for your confirmation.
Please close this issue as your final action :)

**Comment by AussiSG** [comment] 2020-04-30 13:47
Love too ;-)

**Comment by bouwew** [comment] 2020-05-07 15:45
@AussiSG other legacy Anna users report that they can see a tap-icon on the screen when they are tapping hot water. This is also true for your legacy Anna?

**Comment by bouwew** [comment] 2020-05-08 06:28
@AussiSG, please update to version 0.2.4rc0 and let me know if on climate.anna(?) hvac_mode is showing the heating and idle states correctly and if binary_sensor.auxiliary_dhw_state is showing the state of tapping hot water correctly.

**Comment by AussiSG** [comment] 2020-05-08 16:32
@bouwew 
just updated and heating up shows good 
![image](https://user-images.githubusercontent.com/56043947/81426734-e77bf980-9159-11ea-99c0-adf5c5bb6a35.png)
And also the DHW works properly:
![image](https://user-images.githubusercontent.com/56043947/81426912-2dd15880-915a-11ea-9f89-02c185a64c5f.png)

indeed I see a warm water tapping icon on my anna.

**Comment by bouwew** [comment] 2020-05-08 17:01
@AussiSG, that looks good!
Another user pointed me to the heating + hot water tapping case, that case is not correctly shown yet, will try to fix that in v0.2.4rc1.

**Comment by AussiSG** [comment] 2020-05-08 17:05
I think both the icons show on the Anna when tapping hot water ( heating symbol and tapping symbol )
But I am not sure. Need me to verify anything in that case?

**Comment by bouwew** [comment] 2020-05-08 17:06
Yes, please.

**Comment by AussiSG** [comment] 2020-05-08 17:17
Both the icon show on the Anna unit. But the states on the entities show it the proper way in my case
![image](https://user-images.githubusercontent.com/56043947/81430879-83a8ff00-9160-11ea-9cd7-c47fb730fee8.png)

**Comment by bouwew** [comment] 2020-05-08 18:08
The coming update, v0.2.4rc1 should show Mode: Heating and W.W.Afname: on.
But, it will depend on the connected cv-ketel whether this case can be properly shown, or not.

**Comment by AussiSG** [comment] 2020-05-08 18:14
Alright. Will update you when I have installed 2.4rc1 and check that situation

**Comment by bouwew** [comment] 2020-05-09 08:08
@AussiSG version 0.2.4rc1 is available on HACS, please test.

**Comment by AussiSG** [comment] 2020-05-09 10:02
Morning, 
just tested but the HVAC mode did not change to heating.

**Comment by bouwew** [comment] 2020-05-09 10:05
So, version rc0 was ok for you but rc1 is not?
Did you wait long enough, it could take as much as 60 seconds before a change is visible on HA?

**Comment by AussiSG** [comment] 2020-05-09 10:08
Also in version rc0 the HVAC state didn't change to heating when tapping hot water.
Yea it took quite a while before the taping mode went from 'off'  to ' on'

**Comment by bouwew** [comment] 2020-05-09 10:17
Hot water state is shown via binary_sensor.auxiliary_dhw_state.
Also, when only tapping hot water, hvac_mode is supposed to show idle.

**Comment by AussiSG** [comment] 2020-05-09 10:32
> The coming update, v0.2.4rc1 should show Mode: Heating and W.W.Afname: on.
> But, it will depend on the connected cv-ketel whether this case can be properly shown, or not.

I thought you said in this post that also the HVAC / Mode  should change to heating when tapping hot water? 
This because the "flame" symbol is also present on the anna device?

For now the auxiliary_dhw_state shows that the warm water is begin tapped by showing 'on' but this already worked on rc0.

**Comment by bouwew** [comment] 2020-05-09 10:46
This is what should happen now:
- only heating: hvac_mode = heating, .._dhw_state = off
- only tapping hot water: hvac_mode = idle, .._dhw_state = on
- heating and tapping hot water at the same time: hvac_mode = heating, .._dhw_state = on

Before it was so that "hvac_mode = heating" was shown when tapping hot water only, but this was not accepted by a reviewer.

**Comment by AussiSG** [comment] 2020-05-09 10:49
Clear. Did was already good for me on rc0:


> Both the icon( heating symbol and tappig symbol ) show on the Anna unit. But the states on the entities show it the proper way in my case
> ![image](https://user-images.githubusercontent.com/56043947/81430879-83a8ff00-9160-11ea-9cd7-c47fb730fee8.png)

**Comment by bouwew** [comment] 2020-05-09 10:52
Mode = hvac_mode = idle, so the Card is only showing tapping of hot water? So not showing in the proper way I think?

rc could not show the case heating + hot water tapping, it would only show heating.

**Comment by AussiSG** [comment] 2020-05-09 11:03
Correct at that moment I was only tapping hot water. Before I put the temperature up to 24 degrees and it only show the heating but wasn't tapping hot water simultaneous.
The CV is now at max temp. so heating doesn't. 

Can check that some time later on if you want?

**Comment by bouwew** [comment] 2020-05-09 11:06
Sure :) 
Enjoy the nice day, I will do that soon too :)

**Comment by AussiSG** [comment] 2020-05-27 10:58
Goodafternoon guys,

I have update to 0.2.12rc1. Is it correct that I am missing the state of hot water tapping?

**Comment by bouwew** [comment] 2020-05-27 11:36
Sorry to read that. No, it should be there
Is there any error related to plugwise-beta in the HA log?

**Comment by AussiSG** [comment] 2020-05-27 11:42
Not really, Atleast not that I can see.

Here is the start up part of the log file. I do see a sensor calling DHT. But it doenst appear in my entities anymore

https://pastebin.com/MKwkeiT5

**Comment by bouwew** [comment] 2020-05-27 11:48
Could it be that there are 2 binary_sensors now? The original and a binary_sensor.xyz_2?
We made some changes under the hood that could case this.

**Comment by bouwew** [comment] 2020-05-27 12:00
Never mind, I don't see the `dhw_state` in your output. I will check the code...

**Comment by bouwew** [comment] 2020-05-27 12:25
I see another strange thing: from your earlier posts I can see you have a legacy Anna, but I see firmware 3.1.11 in your Pastebin file. That does not match.

**Comment by AussiSG** [comment] 2020-05-27 12:27
Strange indeed. You can see that it s shown properly in home assistant itself ( 1.8.0 ). 
See screentshot hehe

**Comment by bouwew** [comment] 2020-05-27 12:42
@CoMPaTech AussiSG is reporting a new problem.
While checking his logdata out, it shows firmware 3.1.11 while he has a legacy Anna!?

**Comment by bouwew** [comment] 2020-05-27 12:44
@AussiSG can you please grab and attach a recent version of the /core/domain_objects XML-data?

**Comment by CoMPaTech** [comment] 2020-05-27 12:47
That would mean he has `gateway` somewhere in the xml (https://github.com/plugwise/Plugwise-Smile/blob/306065481b18d01b3cff7aafec3b194e6487469a/Plugwise_Smile/Smile.py#L173) indeed in `domain_objects`

**Comment by bouwew** [comment] 2020-05-27 13:09
I think the legacy_anna_2 testfiles are from his system. There's no `gateway` in the core.domain_objects.xml testfile.

**Comment by bouwew** [comment] 2020-05-27 13:14
@AussiSG, on the original topic of your new posting, while working with another user we came to the conclusion that the 0.2.4rc1-code did not work reliably in showing the heating, dhw and heating+dhw states correctly. For now we have disable showing dhw-state, meaning it will always be shown as off. The heating-state is being shown, but also when tapping hot water, so not fully correct. I'm communicating with Plugwise at the moment, trying to resolve this.

**Comment by AussiSG** [comment] 2020-05-27 13:21
@bouwew  sure thing,

here it is : https://pastebin.com/P8D41j9M

**Comment by AussiSG** [comment] 2020-05-27 13:27
Guys... 
![image](https://user-images.githubusercontent.com/56043947/83024290-762fb800-a02e-11ea-8109-d0c6cf5e8d40.png)

I changed my wifi setup a while ago and had to reset the gateway to connect again.
checking the website now shows FW 3.1.11 ????!

**Comment by AussiSG** [comment] 2020-05-27 13:29
I thought 1.8.0 couldnt go to FW 3.1.11  :S

**Comment by bouwew** [comment] 2020-05-27 13:34
@AussiSG Didn't you exchange the original Smile for another one? Or was that someone else?

**Comment by AussiSG** [comment] 2020-05-27 13:37
Yea I did play with the gateway part.
Bought one set from market place but the terminals were fully busted and it didnt work.

So bought a new set , installed new gateway but kept old anna as thermostat.

Running that for quite a while and it was always 1.8.0. 
Also during the last reset the interface still looked like the old 1.8.0.  ( setting up the wifi acces againg ). 
I have done that twice in the last period switching wifi stuff. 
Last time I did a longer reset maybe which initiated a update of some sort....

Sorry man didnt expect this to happen

**Comment by AussiSG** [comment] 2020-05-27 13:40
Should I also replace the anna part with the on I bought? Is there any "upgrade" logic in that thermostat?

**Comment by bouwew** [comment] 2020-05-27 13:42
Yes, I would definitely do that! Maybe the set you bought was not a legacy version but a recent version.

**Comment by AussiSG** [comment] 2020-05-27 13:48
There is nothing to double check it from the outerside is there?
Darn really confused here hehe

**Comment by bouwew** [comment] 2020-05-27 13:49
I'm looking at your xml-file: it does not contain the `domestic_hot_water_state` key. That's why it doesn't work. 
Your XML-file doesn't seem to be complete.

Indeed, try connecting the other Anna to the Smile with the Smile being powered off.

I don't know if there is any difference between a legacy Anna and a newer Anna, sorry.

**Comment by AussiSG** [comment] 2020-05-27 13:55
Working upstairs. Just check the thermostat in the living room and I have some new data in the (old) display :o...

![IMG_20200527_155315](https://user-images.githubusercontent.com/56043947/83028949-631ee700-a032-11ea-8524-66480c165ef7.jpg)
 
One is the time and what is the other one ?

**Comment by bouwew** [comment] 2020-05-27 13:56
Outdoor temperature, the location of the weather-station can be set up via the App/webpage.

Check the webpage for the firmware-version, and check for an update.

**Comment by AussiSG** [comment] 2020-05-27 14:06
![image](https://user-images.githubusercontent.com/56043947/83029926-85fdcb00-a033-11ea-8cbf-851a768abb00.png)
Are there any newer version FW available? I will change the display in a bit and see if t here is any difference.

Regarding the XML file. There is no more data on it. You've received the full version.
Should I make a new one after reconnect the "newer" display?

Als I think it will be wise to delete the Plugwise integration on HA right?

**Comment by bouwew** [comment] 2020-05-27 14:12
Yes, the "new" Anna is now on firmware 4.0.15 I think.

Leave getting XML-data for now. Try to get your devices to work first, and try to get the firmware up-to-date.

And yes, better to delete the Plugwise integration and when your Anna is at the latest firmware, then try adding the Plugwise integration again.

**Comment by AussiSG** [comment] 2020-05-27 15:25
Alright more confused. Installed the Anna which was with the new set ( I think haha )
![IMG_20200527_171709](https://user-images.githubusercontent.com/56043947/83039737-cadb2f00-a03e-11ea-9c2f-a81be1e665be.jpg)

This happens after replugging the smile-t. 

But after updating the screen is different then the other one ??

![IMG_20200527_172417](https://user-images.githubusercontent.com/56043947/83039864-ed6d4800-a03e-11ea-8092-c88b06e2da3a.jpg)

**Comment by bouwew** [comment] 2020-05-27 15:52
There's supposed to be a weather-type icon in the middle, on the top of the screen. Also missing on my Anna when it's sunny.
On what firmware version are you now?

**Comment by AussiSG** [comment] 2020-05-27 16:05
Still on 3.1.11 it keeps on mentioning that its up to date.
I couldn't update on either one of the displays.....

So on my older display it displays a thermometer. And on the new one it doesnt display anything in between.

Are you sure it should display a weather Icon. I cant see anything of that in the manual?

**Comment by bouwew** [comment] 2020-05-27 16:11
I would suggest that you contact Plugwise support and ask them for help. They can probably tell you what hardware you have, based on what's on the labels. Describe what you did, what happened, and probably they can help you to get it fully working.

**Comment by AussiSG** [comment] 2020-05-27 16:24
Yea I will do that. Thanks for the help on that part

To get back on the HA sutff ;-)  After remove and re-adding the integration all looks good 👍 

( Now I also understand the why the outdoor temperature was always inside the logs , I think it was in transition state of some sort..... )


![image](https://user-images.githubusercontent.com/56043947/83046186-f2ce9080-a046-11ea-8619-d296f81e508d.png)

Again sorry for the fuss guys I cant remember if you guys had a lot of troubles with me having a weird Anna/Smile-T combination

**Comment by bouwew** [comment] 2020-05-27 18:40
I'm closing the issue again :)

**Comment by AussiSG** [comment] 2020-05-28 05:27
Just an informational note if some reads the thread a bit. Here was de reaction of Plugwise ( in dutch tho ).

`Wij zijn continu in ontwikkeling met onze producten. Zodoende worden onze producten ook regelmatig ge-update. 
Momenteel zijn wij gefaseerd bezig met de uitrol van de Smile 4. Firmware versie 4.0.15.
​
Hierdoor kan het zijn dat de ene Smile wel al geupdate is en de andere pas over een maand wordt geupdate. 
​
Een aantal van onze Anna/Smile worden niet verder dan 1.8.20 geupdate. Dit omdat deze Anna's bij speciale projecten horen die niet onder onze hoede vallen.
Als gebruikers toch de laatste versie willen ontvangen staat daar een klein bedrag tegen over.`

**Comment by CoMPaTech** [comment] 2020-05-28 06:02
`Now the biting makes sense` :) Thanks for sharing AussiSG!

**Comment by bouwew** [comment] 2020-05-28 07:43
Interesting! I'll double-check this with my contact at Plugwise. If this is really true than the community needs to know this.

**Closed** 2020-05-30 10:45 UTC
Labels: bug, invalid

**Comment by AussiSG** [comment] 2020-05-31 08:44
I can confirm that I have been update to 4.0.19 in the couple of days
![image](https://user-images.githubusercontent.com/56043947/83348317-b3948e00-a32b-11ea-8039-a0017c5ef166.png)
