### ISSUE TITLE
[BUG] `available_schemas` shows only 1 scheme

### ISSUE THREAD

**Issue by fsaris** [plugwise/plugwise-beta#61] opened 2020-05-16 11:25 UTC
**Describe the bug**
The climate attribute available schemas does only show the active scheme

**Expected behavior**
I expected both schemas to be in the list

**Screenshots**
![Screenshot_2020-05-16-13-11-36-162_com android chrome](https://user-images.githubusercontent.com/4019341/82118551-6f748b80-9778-11ea-9a36-9ce5fa3f417a.jpg)
![Screenshot_2020-05-16-13-15-27-190_com android chrome](https://user-images.githubusercontent.com/4019341/82118553-70a5b880-9778-11ea-81fb-363ad06170d5.jpg)

**Home Assistant (please complete the following information):**
 - Version: `0.109.6`
 - Deployment: `hassio` 
 - Installed plugwise version: `plugwise-beta`
 - Installed through `HACS`

**Smile (please complete the following information):**
 - Sort of Smile: `Anna OT`
 - Firmware: [check through the app or the integrations page in Home Assistant]

**Comment by fsaris** [comment] 2020-05-16 11:28
Please let me know if/how I could give you more info

**Comment by fsaris** [comment] 2020-05-16 11:29
Switching schema gives similar results

![Screenshot_2020-05-16-13-28-58-272_com android chrome](https://user-images.githubusercontent.com/4019341/82118712-53251e80-9779-11ea-9e56-1b3da6458161.jpg)

**Comment by bouwew** [comment] 2020-05-16 11:35
Thank you. I can reproduce the issue on my system. I will look into it.

**Comment by bouwew** [comment] 2020-05-16 12:25
Update: it looks like Plugwise has changed something. Before, in firmware 3.1, the schedules also the not selected one(s), were connected to a location. Now, in firmware 4.0, that is no longer the case. The not selected one(s) are no longer connected to a location. So they are not found by our code.
Fixing this will take some time, if we are going to fix it.

**Comment by fsaris** [comment] 2020-05-16 17:10
I see it's a http/xml webservice that's used to communicate with the smile. Is there some documentation of that API or is it all reversed engineered?

**Comment by CoMPaTech** [comment] 2020-05-16 17:33
Unfortunately the latter

**Comment by bouwew** [comment] 2020-05-17 08:14
@fsaris CoMPaTech is seeing two schema's.
Can you please check on your system /core/domain_objects? Find the names of the two schedules and look for a location id under the key <context>. If there are location ids in the context-part under both schedule names, then both schedules can be found by the code.

**Comment by CoMPaTech** [comment] 2020-05-17 09:30
@fsaris what you'd be looking for (I have 'Test' and 'Normal') is the XML construction at (by example): [Test](https://github.com/plugwise/Plugwise-Smile/blob/db36dd87c78501344baa7dc456dfe9a5e7699960/tests/anna_without_boiler_fw4/core.domain_objects.xml#L154) and [Normal](https://github.com/plugwise/Plugwise-Smile/blob/db36dd87c78501344baa7dc456dfe9a5e7699960/tests/anna_without_boiler_fw4/core.domain_objects.xml#L523). If you look at the bottom of the XML-`rule` construct you'll see they both have location `c34c68...` assigned. We're curious to know how yours is comprised.

Be careful when/if you want to share your `/core/domain_objects` as there is sensitive information in there that you might not want disclosed. See [this section](https://github.com/plugwise/Plugwise-Smile/tree/master/tests#important) on what to clean before uploading/sharing.

**Comment by bouwew** [comment] 2020-05-17 09:46
My 2nd schema, not connected to a location in the Plugwise App, looks like this:
```
<rule id="70978c84cee9443eb476d0c2feeedb90">
<name>Test</name>
<description/>
<template id="d0720497b6794471a7ad2f903d4b7cfc" tag="zone_preset_based_on_time_and_presence_with_override"/>
<active>true</active>
<created_date>2020-05-16T13:31:32.649+02:00</created_date>
<modified_date>2020-05-17T10:46:41.712+02:00</modified_date>
<deleted_date/>
<directives>
<when time="[su 07:00,su 23:00)">
<then preset="home"/>
</when>
<when time="[su 23:00,mo 07:00)">
<then preset="asleep"/>
</when>
<when time="[mo 07:00,mo 23:00)">
<then preset="home"/>
</when>
<when time="[mo 23:00,tu 07:00)">
<then preset="asleep"/>
</when>
<when time="[tu 07:00,tu 23:00)">
<then preset="home"/>
</when>
<when time="[tu 23:00,we 07:00)">
<then preset="asleep"/>
</when>
<when time="[we 07:00,we 23:00)">
<then preset="home"/>
</when>
<when time="[we 23:00,th 07:00)">
<then preset="asleep"/>
</when>
<when time="[th 07:00,th 23:00)">
<then preset="home"/>
</when>
<when time="[th 23:00,fr 07:00)">
<then preset="asleep"/>
</when>
<when time="[fr 07:00,fr 23:00)">
<then preset="home"/>
</when>
<when time="[fr 23:00,sa 07:00)">
<then preset="asleep"/>
</when>
<when time="[sa 07:00,sa 23:00)">
<then preset="home"/>
</when>
<when time="[sa 23:00,su 07:00)">
<then preset="asleep"/>
</when>
</directives>
<contexts> </contexts>
</rule>
```

**Comment by CoMPaTech** [comment] 2020-05-17 09:48
Added [this](https://github.com/plugwise/Plugwise-Smile/issues/60) for further information on the module.

**Comment by fsaris** [comment] 2020-05-17 17:31
For me it's also a `<rule/>` tag

```xml
<rule id="ff4518fa747c4eae91a6c7bef8f3af75">
<name>Normale werk week</name>
<description>Provides a week schedule for a Location.</description>
<template id="dc55db850be148209a9dc01521dec6a6" tag="zone_preset_based_on_time_and_presence_with_override"/>
<active>true</active>
<created_date>2019-03-12T12:57:39.740+01:00</created_date>
<modified_date>2020-05-17T17:55:42.683+02:00</modified_date>
<deleted_date/>
<directives>
<when time="[mo 07:30,tu 07:30)">
<then preset="home"/>
</when>
<when time="[tu 07:30,we 07:30)">
<then preset="home"/>
</when>
<when time="[we 07:30,th 07:30)">
<then preset="home"/>
</when>
<when time="[th 07:30,fr 07:30)">
<then preset="home"/>
</when>
<when time="[fr 07:30,mo 08:00)">
<then preset="home"/>
</when>
<when time="[mo 08:00,tu 08:00)">
<then preset="away"/>
</when>
<when time="[tu 08:00,we 08:00)">
<then preset="away"/>
</when>
<when time="[sa 16:00,th 17:00)">
<then preset="home"/>
</when>
<when time="[th 17:00,mo 22:00)">
<then preset="home"/>
</when>
<when time="[mo 22:00,tu 22:00)">
<then preset="asleep"/>
</when>
<when time="[tu 22:00,we 22:00)">
<then preset="asleep"/>
</when>
<when time="[we 22:00,th 22:00)">
<then preset="asleep"/>
</when>
<when time="[th 22:00,fr 22:00)">
<then preset="asleep"/>
</when>
<when time="[fr 22:00,sa 22:00)">
<then preset="asleep"/>
</when>
<when time="[sa 22:00,su 22:00)">
<then preset="asleep"/>
</when>
<when time="[th 08:00,sa 08:00)">
<then preset="away"/>
</when>
<when time="[mo 15:00,fr 15:00)">
<then preset="home"/>
</when>
<when time="[we 15:00,sa 16:00)">
<then preset="home"/>
</when>
<when time="[we 08:00,fr 08:00)">
<then preset="away"/>
</when>
<when time="[fr 08:00,th 08:00)">
<then preset="away"/>
</when>
<when time="[sa 10:00,tu 15:00)">
<then preset="away"/>
</when>
<when time="[tu 15:00,mo 15:00)">
<then preset="home"/>
</when>
<when time="[fr 15:00,we 15:00)">
<then preset="home"/>
</when>
<when time="[sa 08:00,su 08:00)">
<then preset="home"/>
</when>
<when time="[su 08:00,sa 10:00)">
<then preset="home"/>
</when>
<when time="[su 22:00,mo 07:30)">
<then preset="asleep"/>
</when>
</directives>
<contexts> </contexts>
</rule>
```


The selected/active scheme looks like

```xml
<rule id="a23712fdf340486d867f8c739167d4b2">
<name>Zomer stand</name>
<description/>
<template id="dc55db850be148209a9dc01521dec6a6" tag="zone_preset_based_on_time_and_presence_with_override"/>
<active>true</active>
<created_date>2020-05-16T09:27:31.033+02:00</created_date>
<modified_date>2020-05-17T17:55:42.681+02:00</modified_date>
<deleted_date/>
<directives>
<when time="[su 21:00,mo 21:00)">
<then setpoint="10"/>
</when>
<when time="[mo 21:00,tu 21:00)">
<then setpoint="10"/>
</when>
<when time="[tu 21:00,we 21:00)">
<then setpoint="10"/>
</when>
<when time="[we 21:00,th 21:00)">
<then setpoint="10"/>
</when>
<when time="[th 21:00,fr 21:00)">
<then setpoint="10"/>
</when>
<when time="[fr 21:00,sa 21:00)">
<then setpoint="10"/>
</when>
<when time="[sa 21:00,su 21:00)">
<then setpoint="10"/>
</when>
</directives>
<contexts>
<context>
<zone>
<location id="31facf480e934fc8b9eb602e8a87c7c2"/>
</zone>
</context>
</contexts>
</rule>
```

The first one doesn't have a location but both rules are based on template `zone_preset_based_on_time_and_presence_with_override` 
Isn't that a better way to extract them?

**Comment by CoMPaTech** [comment] 2020-05-17 17:34
With an Anna that could make sense but I guess for an Adam you wouldn't know where/if/how to apply it. Might be that the app just forgoes the applicability on a location for Anna's?

**Comment by fsaris** [comment] 2020-05-17 17:34
If I select the other scheme the content of the `<contents>` tag is moved to the other rule

**Comment by CoMPaTech** [comment] 2020-05-17 17:35
What firmware were you on again?

**Comment by fsaris** [comment] 2020-05-17 17:36
> With an Anna that could make sense but I guess for an Adam you wouldn't know where/if/how to apply it. Might be that the app just forgoes the applicability on a location for Anna's?

I just use the web interface of Anna so not sure there. Maybe that's the reason I have different results?

**Comment by CoMPaTech** [comment] 2020-05-17 17:47
> I just use the web interface of Anna so not sure there. Maybe that's the reason I have different results?

Using direct-html mine is now also gone (fw4) as it doesn't have a location anymore, so apparently that's new - I've switch schema's many times a couple of months back because of the initial rewriting.

We'll have to look into if/how we can approach this as for now the active and available schema's are there but there is nothing to do with them. Within the core `climate` component there is just one selector `service` there - which we currently use for `presets`. Additional information is needed also for what it means for Adam-based environments, if those also 'loose' location there must be some magic elsewhere in the data to be able to coherently keep track of what goes where.

Looking back at our code and my previous examples, Plugwise changed their handling. See [here](https://github.com/plugwise/Plugwise-Smile/blob/92b899ae06c2a7c7acbd9e58c9e3e2cb89ae693f/tests/anna_without_boiler_fw3/core.domain_objects.xml#L522), they used to flag `active` to True/False, but apparently rules just stay `active` True now. We'll get back on this, but we need to see if and how we can approach this.

**Comment by CoMPaTech** [comment] 2020-05-17 17:58
Created https://github.com/plugwise/Plugwise-Smile/issues/63

**Comment by bouwew** [comment] 2020-05-17 17:59
When it was only the Anna, only looking for the tag was OK, but now with the Adam, and the Anna-firmware looking more and more like the Adam-firmware, we are looking for the tag and the connected location. When the location is no longer there, blame the Adam-firmware, we either need to skip it, or find another way.

As long as it is not easy to change schema from HA, I don't see a need to show available_schemas as an attribute.

**Comment by fsaris** [comment] 2020-05-17 18:27
> As long as it is not easy to change the selected schema from HA, I don't see a need to show available_schemas as an attribute.

You could expose/implement a service for that in this integration :wink: 


Maybe you could add a fallback for Anna devices to add all active schemes to the default location. Not sure if you use the location option at all for Anna. This is not something that is exposed to HA is it?

**Comment by bouwew** [comment] 2020-05-17 18:43
Yes, but it's much more convenient doing it via the App. As doing it in the App, via select/click, will not become available in HA.

Yes, we use the location for Anna, the code I developed originally for the Adam also worked on the Anna, no changes needed :)

Maybe you can have a look at the Plugwise_Smile code?

**Comment by CoMPaTech** [comment] 2020-05-17 18:50
Hmmm, I wrote a comment here, but apparently it got lost ... I think I've outlined how we approach in https://github.com/plugwise/Plugwise-Smile/issues/60 and created a pending decision in https://github.com/plugwise/Plugwise-Smile/issues/63. 

Not too get lost in numbers here, but #62 was just merged - that's not necessarily fixing the bug but at least alleviating the interpretation within HA.

**Closed by CoMPaTech** 2020-05-17 18:50 UTC
Labels: bug

**Comment by fsaris** [comment] 2020-05-17 19:16
Tnx for all your efforts :+1: 

I can find the info in the XML now. Next is find my way around python to see if I could help you in some way or another :smile:

**Comment by bouwew** [comment] 2020-05-18 06:56
@fsaris Please test Plugwise-beta v0.2.9rc0, available on HACS.

**Comment by fsaris** [comment] 2020-05-18 09:11
Installed it yesterday evening already, will report back
