### ISSUE TITLE
[BUG] No matching statistics found (last HA update)

### ISSUE THREAD

**Issue by malosaa** [plugwise/plugwise-beta#189] opened 2021-08-07 14:22 UTC
Hi Bouwe,

I don't know if this is an bug or its not supported yet.
But after i upgraded to last HA i see the new energy tab.
When i want to add the energy source its not showing up anything. 
only this: No matching statistics found

Any idea why? 
Or is it not supported yet.

//update
check from here, i think you as the developer need to report it
this video is from the livestream of the new release.
https://youtu.be/VLiqDkam33k?t=5594

and i see all devices need to include this to function:
device_class: energy
state_class: measurement

Regards

**Comment by bouwew** [comment] 2021-08-07 15:41
Yes, working on it. You can enable "show beta" in HACS, you should see v0.17.0a2 or higher, please test that version.

**Comment by malosaa** [comment] 2021-08-07 15:55
ok ill do now

**Comment by malosaa** [comment] 2021-08-07 16:01
Ok, i see some of them in the list,

to test out, what one do i need to select for consumption, return, and solar panels?
Because i think the POINT device is the one who gives the actual consume, but not sure if thats the one to use in here, its not in the list.

**Comment by bouwew** [comment] 2021-08-07 16:02
Wait, you would want this for the P1-legacy integration, correct?

**Comment by malosaa** [comment] 2021-08-07 16:03
On this device i'm on the last plugwise-beta not the legacy, thats on my other device.

**Comment by bouwew** [comment] 2021-08-07 16:03
For HA Energy use the cumulative sensors. Those are working for me.
I have also added some interval-sensors but they don't seem to work.

**Comment by bouwew** [comment] 2021-08-07 16:05
But, you'll need to wait at least one hour before there is anything visible in the graph.
This is a part of my graph:
![image](https://user-images.githubusercontent.com/11290930/128606370-d5d4df34-edd4-415c-99ee-f0427669cde4.png)

**Comment by malosaa** [comment] 2021-08-07 16:07
yes thats no problem, right now i don't know what one to choose.
Does it change automatically to peak and offpeak, there is also a device called: sensor.p1_net_electricity_cumulative
is that the one to use for consumption right?

**Comment by bouwew** [comment] 2021-08-07 16:08
No, you should use the cumulative_peak and _off_peak sensors, nothing else.

**Comment by bouwew** [comment] 2021-08-07 16:10
And you should separate between consumption and production, so use in total 4 cumulative sensor when you also have production and are exporting energy to the grid.

**Comment by malosaa** [comment] 2021-08-07 16:11
aah yes i see u can add both.

well i guess for solar panels i need to use an other device right?

**Comment by bouwew** [comment] 2021-08-07 16:12
The net-sensor sums: (consumption - production), for people that want to know the net_cumulative number.
But this one is not useful in HA Core Energy.

**Comment by bouwew** [comment] 2021-08-07 16:13
There is a trick you can use:

Put this in configuration.yaml:
```
  customize_glob:
    sensor.*_energy:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: energy
      state_class: measurement
```

**Comment by bouwew** [comment] 2021-08-07 16:14
You will need to change the `sensor.*_energy` part.

**Comment by bouwew** [comment] 2021-08-07 16:16
Make sure to let me know if it works for you, the plugwise-beta v0.17.0a4 version.
I need positive feedback from several users before I make it into a formal release.

**Comment by malosaa** [comment] 2021-08-07 16:17
yeah i did that, sadly it doesnt work with utility_meter:

i did make it like this and it works good aswell:

template:
  - sensor:
    - name: lol_energy
      state: "{{ states('sensor.my_plant_total_output_power') }}" 
      unit_of_measurement: 'kWh'
      state_class: measurement
      device_class: energy

**Comment by malosaa** [comment] 2021-08-07 16:19
I must say it works good, 
i will restart now and check everything and i report back

**Comment by malosaa** [comment] 2021-08-07 16:21
Well i did a restart, everything (electricity) shows up fine,
i will report back once i got some bars up and running.

Many thanks for this awsome support and quick fix!!

**Comment by malosaa** [comment] 2021-08-07 18:16
its 2 hours ago, still no graph here.

regards

**Comment by malosaa** [comment] 2021-08-07 18:20
![image](https://user-images.githubusercontent.com/13116501/128610307-b5b219a0-0698-43e4-aa2d-23e2289c5483.png)

**Comment by malosaa** [comment] 2021-08-07 20:05
still nothing, 
this is how i did set it up 


![image](https://user-images.githubusercontent.com/13116501/128612632-45b7a814-0852-498a-a37c-6e2d5588c5d8.png)

**Comment by bouwew** [comment] 2021-08-08 07:58
@malosaa I have also made a new version of p1-legacy, v0.2.0a0.
Please test and let me know if it works, or if there are problems.

**Comment by malosaa** [comment] 2021-08-08 08:44
ok ill test now

**Comment by malosaa** [comment] 2021-08-08 09:48
Sorry for the late reply, had an internet issue i just fixed. 
I'm testing on my opther system, no graphs yet. probably to soon.

I really don't know why this system is not graphing at all, i even add my solar input device, also no graph from that device..
Did i do something wrong in the settings ?

**Comment by malosaa** [comment] 2021-08-08 09:53
In my Yaml i have this at the top under default config 

```
homeassistant:
  customize_glob:
    sensor.*_energy:
      last_reset: "2021-08-05T08:05:00+00:00"
      device_class: energy
      state_class: measurement

```
and i have 1 template that gets the data from utility_meter becasue growatt is W and not kwh

```
template:
  - sensor:
    - name: growattbruto_energy
      state: "{{ states('sensor.growatt_b1') }}" 
      unit_of_measurement: 'kWh'
      state_class: measurement
      device_class: energy 
      attributes:         
          last_reset: "2021-08-05T08:05:00+00:00"
```

i did nothing else, and added the sensors of your plugin correct like the screenshot. but nothing showing up

**Comment by bouwew** [comment] 2021-08-08 09:54
No problem :)
We (us codeowners) are thinking that there is an issue with the Energy integration expecting kWh-numbers while the Plugwise-beta integration is providing Wh-numbers.

**Comment by malosaa** [comment] 2021-08-08 09:55
Yes, but i already did add the growatt sensor, thats showing up as kwh now, but also not graphing..

**Comment by bouwew** [comment] 2021-08-08 10:06
My coding-colleague sees nothing or very small numbers, strange.
There are a lot of unknowns about this new Core feature :)

**Comment by malosaa** [comment] 2021-08-08 10:09
I will need to find out why it doesnt graph.. 
So this beta version (not legacy) works for you ?

**Comment by bouwew** [comment] 2021-08-08 10:13
I don't have a P1. My coding-colleague has one, he has the same problem as you I think.

Let me see if I can turn the Wh-numbers into kWh-numbers in an easy way.

**Comment by malosaa** [comment] 2021-08-08 10:17
I don't know if thats the issue, because i have a growatt sensor reporting in kwh, also no graph with it.

**Comment by bouwew** [comment] 2021-08-08 10:31
I think I've found a bug, a new version will be up soon.

**Comment by malosaa** [comment] 2021-08-08 10:44
ok sounds good, awaiting to test

**Comment by bouwew** [comment] 2021-08-08 10:53
Please try v0.17.0a6.

**Comment by malosaa** [comment] 2021-08-08 10:59
i did update, this time i added the P1 Electricity Produced Off Peak Cumulative as an individual aswell, but not see any updates.

**Comment by bouwew** [comment] 2021-08-08 11:09
That looks good. Now wait a few hours... :)

**Comment by malosaa** [comment] 2021-08-08 12:37
Well, its 2 hours later, still no graph ;(

**Comment by CoMPaTech** [comment] 2021-08-08 12:41
I've got the initial number there, still waiting for the turnover to 3pm here

**Comment by malosaa** [comment] 2021-08-08 13:05
@CoMPaTech 
when did u start ? for me still nothing... 
Really don't know whats going on.

**Comment by CoMPaTech** [comment] 2021-08-08 13:11
Checking again over here what's going on ... i have the initial number from around 1pm but nothing after that

**Comment by malosaa** [comment] 2021-08-08 13:15
there must be some sort of a issue, there must be a file containing that information of that new energy.. maybe our logs are bad and thats why it doesnt show up...

**Comment by malosaa** [comment] 2021-08-08 13:20
I did ask frenck if there is a file containing all that info so i can delete it and start over.

**Comment by CoMPaTech** [comment] 2021-08-08 13:21
It might be in the db already ... the energy file in .storage is just the dashboard config :(

**Comment by malosaa** [comment] 2021-08-08 13:26
damn,

What happens if u add this : sensor.p1_electricity_produced_off_peak_cumulative as a single device in your dashboard?
for me it doesnt report anything.

well look at this, it does report but not at the dashboard.
![image](https://user-images.githubusercontent.com/13116501/128633517-f530cb77-df4b-44c9-be97-b7c17819bc19.png)

**Comment by malosaa** [comment] 2021-08-08 13:35
there is a new core version available,

Newest Version
core-2021.8.4

**Comment by malosaa** [comment] 2021-08-08 14:12
i did update to last core version, and i did delete my settings in the energy tab with nothing.
after that i did setup again the devices and see in 2 hours if they show up.

Even when i did remove all devices from  --> configuration --> energy  it still showed up the energy page with no devices.. still showing home and grid.. 

but i don't get that page like i had in the beginning when nothing was setup.. when i press the icon left and not in the configuration, normally i get a message saying nothing has been setup and i can go into the ---> configuration ---> energy to put the devices in there..

**Comment by malosaa** [comment] 2021-08-08 14:21
well i'm getthing this error on the last update of core 

```
Logger: frontend.js.latest.202108040
Source: components/system_log/__init__.py:190
First occurred: 16:20:13 (1 occurrences)
Last logged: 16:20:13

https://192.168.1.25:8123/lovelace/0:0:0 Uncaught
```

u have that to if u refresh /energy page ? 

@CoMPaTech

**Comment by bouwew** [comment] 2021-08-08 14:40
How does the history-graph look like of the p1-cumulative-sensors?
Something like this?
![image](https://user-images.githubusercontent.com/11290930/128635888-b9e9f7dd-4c9d-4946-979d-2a85861c1dfb.png)

**Comment by bouwew** [comment] 2021-08-08 14:49
After thinking about it, I think the Energy-graph will start showing something after midnight. The graph starts at 00:00hrs and shows the energy-use per hour for one day (24hrs).

**Comment by malosaa** [comment] 2021-08-08 14:53
@bouwew 

i think there is the issue 

![image](https://user-images.githubusercontent.com/13116501/128636274-b964c396-e7ef-4465-a2e2-4ac2ce69da6e.png)

**Comment by CoMPaTech** [comment] 2021-08-08 14:55
It might also be that there is data but we just don't see it ... I now have a big spike (14kWh) at noon today ... so my guess is it probably is working, but I don't see the delta until that large spike is gone
(due to the Wh => kWh conversion)

**Comment by malosaa** [comment] 2021-08-08 14:57
consumed if fine tho

![image](https://user-images.githubusercontent.com/13116501/128636401-b59bcd42-4d0e-4d27-b312-431ecf336864.png)

I don't know @CoMPaTech  i still dont have any graphs, like they said in the livestream video after 2 hours it must show up.

**Comment by bouwew** [comment] 2021-08-08 14:59
That graph is what I expect to see, so the basis is good. The rest is just patience I guess :(
Have a look at it first thing tomorrow morning :)

**Comment by malosaa** [comment] 2021-08-08 20:29
@bouwew 

i did check, still nothing, i will check tomorrow morning again.
Also did ask an other guy he said he had the graphs within 3 hours.. so maybe there is something wrong.

I will let u know tomorrow morning.

regards

**Comment by CoMPaTech** [comment] 2021-08-09 04:58
It's working here (tried with deleting my db, so I knew that worked, but restored the db and let it sit overnight, I've got graphs now)

**Comment by malosaa** [comment] 2021-08-09 07:52
for me not even 1 graph, @bouwew 

@CoMPaTech  what did you do  si it worked ? 
i also did find a file energy in config/.storage/energy but im not able to open or whatever.

**Comment by CoMPaTech** [comment] 2021-08-09 07:54
Don't worry about that file, it doesn't contain anything. Does yours show 'a large value' (like 24mW or something) still or doesn't it show anything at all (like you posted https://github.com/plugwise/plugwise-beta/issues/189#issuecomment-894689098)

**Comment by malosaa** [comment] 2021-08-09 07:55
@CoMPaTech 
not showing 1 thing at all.

**Comment by malosaa** [comment] 2021-08-09 07:57
well i deleted that energy file and now i get a setup again. i gonna re-add the devices.

but how and what database did you delete ?

**Comment by malosaa** [comment] 2021-08-09 08:10
@CoMPaTech 
What database did you delete ? 

I just deleted the file in .config/energy and did set it up again.. waiting now till 12:30 and see if there are graphs.
They should show up within 3 hours.
If not i want to try your way.

**Comment by malosaa** [comment] 2021-08-09 14:00
@CoMPaTech  @bouwew 

Well i'm on mariaDB so there is no database to delete... atleast i don't even know how to access it, because its not available trough the samba plugin.(if u guys know how i can access it let me know, because i cant see how big it is)


What i did just now is change the mariaDB name in the config and restart HASS it did reset to 0. ill report back in few hours.

**Comment by malosaa** [comment] 2021-08-09 17:52
Still no graphs,
i'm really wondering if it has something to do with my database...

i have this in my yaml,
recorder:
db_url: mysql://*****:******@core-mariadb/************

if thats not the case than i'm out of options.
More people saying that it needs to graph within 2 hours if there is data incoming.
When the second hour starts it must graph so it compairs whit the first time, so 1 hour before.

**Comment by malosaa** [comment] 2021-08-10 07:02
@bouwew 

this morning after 14 hours still no graphs.
on my other system same thing.

**Comment by bouwew** [comment] 2021-08-10 10:56
Sorry, I can't help you any further.
The cumulative kWh sensors are providing the correct output so the problem must be somewhere else.
I wanted to point you to the Energy-topic on the HA Community forum but I see you are already posting in that topic.

**Comment by bouwew** [comment] 2021-08-10 11:09
I was looking at the recorder-options, at the db_URL's, I am wondering, is the URL you have in configuration.yaml correct?
Have you included the `?charset=utf8mb4` part?

**Comment by malosaa** [comment] 2021-08-10 11:15
@bouwew 
i did even that line, so it started a new default database,
actually i find out a little problem what can cause this issue, after i did set it to default by deleting the full line recorder: it created a homeassistant database. 
it gets corrupted after 3 hours, but when i open that db and check the logs are stored 2 hours before my time.
like my time is 13:00 and the same thing is stored 10:00..

i did really check every time setting, its all setup correct.

**Comment by malosaa** [comment] 2021-08-10 11:24
maybe it's my system.

what i gonna do is install a clean version of homeassistant, trough virtualbox and try again.
I will this time use the legacy plugin of the p1 
see if it works then.

i let u know

**Comment by malosaa** [comment] 2021-08-10 12:28
@bouwew 

the gas device  broke again on the beta p1 legacy.

regards

**Comment by bouwew** [comment] 2021-08-10 12:59
You mean the p1-legacy component has the same problem as you've reported for plugwise-beta?

Well, then there's nothing I can do: I have now way of finding out how Homeseer obtains the data from the P1. As the Homeseer sourced is closed.
Can you check what is shown on the P1 local website? When you browse to the IP-address of the Smile P1 you should see some kind of dashboard, maybe you need to login.
Does the value you see on the Dashboard correspond with the value on Homeseer?

**Comment by malosaa** [comment] 2021-08-10 13:50
@bouwew 

maybe i said it wrong, 
last time when i tested out the legacy version the 2 gas versions got fixed, when u updated them for the new energy db it not working

**Comment by bouwew** [comment] 2021-08-10 14:34
How do you know the Homeseer value is correct? Can you check this via the display of the gasmeter?

**Comment by malosaa** [comment] 2021-08-10 18:37
sorry for the late reply,
the value of homeseer is correct, i can see that if i check it local on the plugwise app.

but i do see i installed your repo for the legacy one, but keeps installing your plugwise beta p1 plugin instead of the legacy one

@bouwew

**Comment by bouwew** [comment] 2021-08-10 18:43
You mean that after you've installed the Plugwise P1 legacy component vai HACS, only the Plugwise beta component shows up in the list of Integrations?

**Comment by malosaa** [comment] 2021-08-10 19:06
no, i have the beta installed. with adam, stick, anna.
but if i want to install p1, it installs the one from the beta package instead of the legacy, thats why the gas devices are not working

**Comment by bouwew** [comment] 2021-08-10 19:11
Yeah, you can't have both, you must remove the plugwise-beta component first, via HACS.

**Comment by malosaa** [comment] 2021-08-10 19:12
that i will not be able to use stick and adam and anna right ?

**Comment by malosaa** [comment] 2021-08-10 19:18
aah im such a idiot. i need to config it trough the yaml.. hehe

**Comment by bouwew** [comment] 2021-08-10 19:21
Sorry, I'm wrong, you can use both at the same time. Just don't load the plugwise-beta integration for the P1.

**Comment by bouwew** [comment] 2021-08-10 19:22
Please note, plugwise-beta v0.17.0 was just released.

**Comment by malosaa** [comment] 2021-08-10 19:57
Well, atleast everything working, i did debug so much that i found an error on the virtualbox image of homeassistant.
There was an error because of the new update that caused my databases go corrupt, but the bad part is if u use mariaDB u can't see anything, it does not say any error in the logs..
So i deleted the lines of recorder and start making again a new default database, and there ive seen anerror corrupting my db while making a new one every 2 hours, thats why i never seen the bars.

I downloaded a new version, started from scratch and it works.
took me a whole day to rebuild my db like i had before.

atleast everything works and also Plugwise :) 

many thanks for helping !!

**Comment by malosaa** [comment] 2021-08-10 19:58
> Please note, plugwise-beta v0.17.0 was just released.

i did install it

**Comment by bouwew** [comment] 2021-08-11 06:20
I'm glad that you finally have it working. Yes, HA Core can be a headache sometimes but the devs are quick in fixing stuff once they know something is broken.

Ok, so now you are using the P1-legacy integration to read out the P1-data? That does work correctly now? 
Also, which version did you install?

**Comment by malosaa** [comment] 2021-08-11 10:17
@bouwew 

sorry again for the late delay.. 
Well, the legacy doesnt graph again.

yesterday when i changed it to the legacy by deselecting everything in energy and uninstalling the p1 beta, and configuring the legacy p1 and restarting homeassistant, it did not graph overnight.. sadly again this issue...

**Comment by malosaa** [comment] 2021-08-11 10:18
i'm testing again to let it graph with the p1 beta version, if that doesnt work i think the legacy version is corrupting something in homeassistant that doesnt let it graph anymore..

**Comment by malosaa** [comment] 2021-08-11 10:22
it's really annoying,

look i get this error again and i don't even knwo whats causing it.. i did clean install homeassistant yesterday.

Logger: homeassistant.components.recorder
Source: components/sensor/recorder.py:81
Integration: Recorder (documentation, issues)
First occurred: 11:12:00 (2 occurrences)
Last logged: 12:12:00
```

Error while processing event StatisticsTask(start=datetime.datetime(2021, 8, 11, 8, 0, tzinfo=datetime.timezone.utc)): 'bar'
Error while processing event StatisticsTask(start=datetime.datetime(2021, 8, 11, 9, 0, tzinfo=datetime.timezone.utc)): 'bar'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 623, in _run_event_loop
    self._process_one_event_or_recover(event)
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 632, in _process_one_event_or_recover
    self._process_one_event(event)
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 738, in _process_one_event
    self._run_statistics(event.start)
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 721, in _run_statistics
    if statistics.compile_statistics(self, start):
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 303, in wrapper
    return job(instance, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 154, in compile_statistics
    platform_stats.append(platform.compile_statistics(instance.hass, start, end))
  File "/usr/src/homeassistant/homeassistant/components/sensor/recorder.py", line 227, in compile_statistics
    unit, fstates = _normalize_states(entity_history, key, entity_id)
  File "/usr/src/homeassistant/homeassistant/components/sensor/recorder.py", line 199, in _normalize_states
    fstates.append((UNIT_CONVERSIONS[key][unit](fstate), state))
  File "/usr/src/homeassistant/homeassistant/components/sensor/recorder.py", line 81, in <lambda>
    PRESSURE_BAR: lambda x: x / pressure_util.UNIT_CONVERSION[PRESSURE_BAR],
KeyError: 'bar'
```

**Comment by bouwew** [comment] 2021-08-11 13:13
The above error is a recorder-related error. I suggest you create an issue for this in the HA Core github: https://github.com/home-assistant/core

There should be no difference between p1-legacy and plugwise-beta: when you can see a good history-graph as we talked about in above messages, then it is working.

Which P1-legacy version are/were you using?

**Comment by bouwew** [comment] 2021-08-11 13:31
Last p1-legacy  = v0.2.0a0?

**Comment by malosaa** [comment] 2021-08-11 14:04
@bouwew 

i really don't understand, i installed only plugwise anna and adam, and no bar is showing up..

i detected a change see this screenshot

![image](https://user-images.githubusercontent.com/13116501/129043411-b8a0be85-74db-476b-b0f9-b7a7924fab64.png)

**Comment by malosaa** [comment] 2021-08-11 14:42
i uploaded my database only containing the produce from today till now, remember time is -2 hours 

https://pastebin.com/7URPMPBn

**Comment by malosaa** [comment] 2021-08-11 15:34
fenck said this: 
This is correct, databases stores time in UTC, this is the correct behavior and not part of the issue you are looking after.

he ask me whats going on, i think he gonna help me now aswell, i did again delete the db and try again..

**Comment by malosaa** [comment] 2021-08-11 15:43
but why that first bar showing up then ?

**Comment by malosaa** [comment] 2021-08-11 15:54
@bouwew 
u sure its that problem, as it did graph a bar before.

**Comment by malosaa** [comment] 2021-08-11 16:05
ok, i manually installed it because it was not visible in github and hacs 

i did delete the database again and the value's are in kWh.. lets wait again 2 hours.

but i don't know why it did display a graph before with wh
i report back.

**Comment by bouwew** [comment] 2021-08-11 16:07
You can force a manual update in HACS by, in the integration-tile, pressing the 3 vertical dots, press Update Information.

**Comment by bouwew** [comment] 2021-08-11 16:08
Not sure if that solves the problem, but I noticed there was a bug that needed fixing :)

**Comment by bouwew** [comment] 2021-08-11 16:10
Now I need to implement one more feature in p1-legacy, then p1-legacy and plugwise-beta are 100% equal in output, but that will take some time, I need to find some way to test my code.

**Comment by malosaa** [comment] 2021-08-11 16:12
ok cool,
i can test for you, also the update interval of the legacy doesnt work. it stays 30 seconds even changing to 5.

**Comment by bouwew** [comment] 2021-08-11 16:16
p1 beta? You mean plugwise-beta?

I told you, plugwise-beta does not support your p1. It's too old.

**Comment by malosaa** [comment] 2021-08-11 16:20
> p1 beta? You mean plugwise-beta?
> 
> I told you, plugwise-beta does not support your p1. It's too old.

yes i know, it even worked together with no problems, plugwise beta does support my p1 electricity , only not gas.

**Comment by bouwew** [comment] 2021-08-11 17:09
Using plugwise-beta for energy and using p1-legacy for gas means that two integration are "talking" to the P1. I know the P1 is not very powerful so this is a risk. That's why I'm advising you to only use the p1-legacy for the P1, and not use plugwise-beta.

**Comment by malosaa** [comment] 2021-08-11 17:20
yeah i know, but right now i'm using it to ping from homseer and from home-assistant.
but actually on p1-legacy the update function doesnt work. it stays 30 seconds, even if i make it 10 seconds.

**Comment by malosaa** [comment] 2021-08-11 17:37
i think its still not working,

when i check the sql database not even 1 statistic is showing up. it should report after 1 hour of recording.. 
its almost 2 hours.

this guy posted a way to debug it easy trough mysql database plugin.
https://community.home-assistant.io/t/energy-management-in-home-assistant/326854/455?u=malosaa

**Comment by malosaa** [comment] 2021-08-11 18:19
aah good, well now it doesnt work again. 
Franck did say it has to do with the p1 coding, but i doubt it as it doesnt work again.

i gonna restore back to where it worked and test again, as the wh did graph for me..

**Comment by malosaa** [comment] 2021-08-11 18:24
i can confirm when i did put back the backup and checked with sql db it showed the statistics normally.

**Comment by bouwew** [comment] 2021-08-11 18:25
I've just added the two p1-cumulative-consumption sensors to my Energy dashboard. I will let you know what happens over here.
![image](https://user-images.githubusercontent.com/11290930/129082860-dbc21efb-ec68-45af-a58b-7a77240681b8.png)
![image](https://user-images.githubusercontent.com/11290930/129083020-4f05f2db-4352-46fa-acea-0b8780c762c3.png)

**Comment by malosaa** [comment] 2021-08-11 18:34
ok great, it exactly updates in 2 hours. 

ill report back in 2 hours

**Comment by bouwew** [comment] 2021-08-11 18:38
If you want to change the update interval you need to do two things: 1) change the number 30 to e.g 10 2) add this last line to configuration.yaml:
```
  - platform: plugwise_p1_legacy
    host: 10.10.10.01
    username: smile
    password: abcdefgh
    resources:
      - electricity_consumed_point
      - electricity_consumed_offpeak_interval
      - electricity_consumed_peak_interval
      - electricity_consumed_offpeak_cumulative
      - electricity_consumed_peak_cumulative
      - electricity_produced_point
      - electricity_produced_offpeak_interval
      - electricity_produced_peak_interval
      - electricity_produced_offpeak_cumulative
      - electricity_produced_peak_cumulative
      - net_electricity_point
      - net_electricity_cumulative
      - gas_consumed_interval
      - gas_consumed_cumulative
    scan_interval: 10 ### <-- add this line ###
```

**Comment by bouwew** [comment] 2021-08-11 18:40
I've done this, now I see updates every 20 seconds(?) instead of per minute.

**Comment by malosaa** [comment] 2021-08-11 18:45
aah ok thanks, well i did notice another thing.

when i did set back the update the graphs worked with wh, really weird.

**Comment by malosaa** [comment] 2021-08-11 18:53
it shows up Wh in the sql browser under entity_id , but in statistics it shows up as kWh.

now at 21:00 - 21:15 it should create a new statistic file, if not i gonna full reset my system and rebuid again.

**Comment by malosaa** [comment] 2021-08-11 19:15
u gotta be kidding me, 

i think i found out the issue, its a template i think.. its showing up now. i gonna put the backup back to 1 hour ago and change the same thing lets seen

**Comment by bouwew** [comment] 2021-08-11 20:21
I have a bar: 
![image](https://user-images.githubusercontent.com/11290930/129097676-4c764de5-f7d3-4098-8172-ee89e13b945d.png)

**Comment by bouwew** [comment] 2021-08-12 06:31
And no more bars:
![image](https://user-images.githubusercontent.com/11290930/129148750-8ef28d8a-f65a-44a5-a2d8-46d9d19b93dc.png)

**Comment by malosaa** [comment] 2021-08-12 07:19
wow, for me its not graphing at all again.. i left it overnight... 
i really don't know whats causing this problem, i thought it was an config error or templaten, but no...

**Comment by malosaa** [comment] 2021-08-12 07:36
getting now this error again,
`Error while processing event StatisticsTask(start=datetime.datetime(2021, 8, 12, 2, 0, tzinfo=datetime.timezone.utc)): 'bar'`

if i set back the backup to when u had the add-on not changed to kWh it graphs normally...

**Comment by malosaa** [comment] 2021-08-12 09:26
@bouwew 

the devs fixed the log issue, well see it in the  2021.8.7 version.
if thats working, than we did spend time debugging for nothing.... 

https://github.com/home-assistant/core/issues/54495

**Comment by bouwew** [comment] 2021-08-12 09:50
V0.2.0a2 is available. I found one small bug, an incorrect device_class for the net_elec_cumulative sensor.
I'm not sure if that has any effect in relation to the problems that you are having. But I thought let's fix it anyway.

**Comment by malosaa** [comment] 2021-08-12 16:34
> V0.2.0a2 is available. I found one small bug, an incorrect device_class for the net_elec_cumulative sensor.
> I'm not sure if that has any effect in relation to the problems that you are having. But I thought let's fix it anyway.

thanks, ill update once 2021.8.7 is released, i let u know. but if plugwise p1 works for u than i think this issue is solved :)

**Comment by bouwew** [comment] 2021-08-12 17:52
V0.2.0 is available: all interval sensors now have valid last_reset timestamps. Now the sensors provided by p1-legacy have the same attributes as the sensors provided by plugwise-beta.

**Comment by bouwew** [comment] 2021-08-12 18:00
And, yes, please close this issue as the p1-legacy integration is working well, with the default recorder-database that is.
Your problem seem to be caused by your use of MariaDB.
Anyway, good luck solving you problem!

**Comment by malosaa** [comment] 2021-08-12 18:12
@bouwew i am using default recorder-database not maria db.
in the last core version there is an error they did fix it in .8

thanks for the update

**Closed** 2021-08-12 18:14 UTC
Labels: bug
