### ISSUE TITLE
Plugwise features loria  extra entities

### ISSUE THREAD

**Issue by Wishdoc** [plugwise/plugwise-beta#301] opened 2022-09-28 20:04 UTC
### Describe the solution you are looking for

Plugwise has released 2 features for the loria duo.  The specific loria duo feature and the cooling feature.
[Loria feature](https://www.plugwise.com/product/loria-thermastage-feature/)

this allows the heating of the boiler water and also coolingfunction to be controlled.  as well as some additional features. 
it would be nice if these features could be included as an entity in home assistant

### Is your feature request related to a problem? (optional)

Not related to a problem 

### What type of installation are you running?

Home Assistant Core

### How did you install plugwise-beta?

Cloned from GitHub

### What kind of Plugwise device is having issues?

Smile: Anna

### What firmware version is your Plugwise product at?

4.3.8

### Your setup

Anna with Loria feature and cooling feature for Loria 

### Additional context

![B865EF39-8BE2-43AB-BD3C-91EA6F822704](https://user-images.githubusercontent.com/102429191/192878066-1533ec8d-2a57-4994-9727-36af27950b20.jpeg)
![E5EC56A9-D8EA-4B9A-82E6-860139E520C0](https://user-images.githubusercontent.com/102429191/192878071-9f202821-a6dc-4284-87ed-99aba3ce28cf.jpeg)
![A9FD50C6-3575-4197-8B1D-243336482A8F](https://user-images.githubusercontent.com/102429191/192878073-dbbc079c-6742-40e3-aace-f5930b6b3b3d.jpeg)

**Comment by bouwew** [comment] 2022-09-29 06:51
@Wishdoc thanks for your request. We were not in contact with a Loria owner yet :)

The coming v0.27.0-release of plugwise-beta should support the Loria cooling feature. This support was implemented with the help of Plugwise. Please install and test this release when it becomes available (soon).

For your request, please provide the xml-data from your system as described here: https://github.com/plugwise/python-plugwise/tree/main/userdata#sharing

Please send the xml-files to "bouwe at westerdijk point info" (please use a proper email-address format :) )

**Comment by Wishdoc** [comment] 2022-09-30 07:29
Hi, I installed the latest version.  And unfortunately the cooling is not working yet.  see attached screenshot for the message

there doesn't seem to be a switch for turning on the cooling either.  also added a screenshot of the entities![image](https://user-images.githubusercontent.com/102429191/193215461-f409d21e-fea1-4485-9e3e-093ceefda0f0.png)
![image](https://user-images.githubusercontent.com/102429191/193215481-406222e6-4a91-4727-bc2e-8f89f0ba40c1.png)![image](https://user-images.githubusercontent.com/102429191/193215500-3965362c-fc7a-4840-bd80-0235376c6bb7.png)

**Comment by bouwew** [comment] 2022-09-30 16:51
@Wishdoc which other options do you see under "Werking"?

**Comment by Wishdoc** [comment] 2022-09-30 18:04
![image](https://user-images.githubusercontent.com/102429191/193330054-4ee02a43-4911-4e46-bf59-4f8e6480de61.png)

Both cooling as auto I tried but don't work

**Comment by bouwew** [comment] 2022-09-30 18:34
Ok, that clarifies it, this is not for switching to cooling, it is for switching between `auto` ( = schedule mode) and non-schedule mode (= `koelen` or `verwarmen`). I need to fix the code so that only `auto` and `verwarmen` or `auto` and `koelen` are shown.

Many Core users are confused by this :)

**Comment by bouwew** [comment] 2022-10-02 12:12
@Wishdoc please update to plugwise-beta v0.30.a1 (make it visible in HACS via Plugwise Beta custom component --> 3 vertical dots --> Redownload --> toggle Show Beta to on) and test.

There should be a Cooling switch, there should be a DHW mode selector and under "Werking" there should only be two options: auto and verwarmen, or auto and koelen.

Please toggle the Cooling switch and select a few DHW modes to see if everything works correctly.

If there's anything out of order, please let me know.

**Comment by Wishdoc** [comment] 2022-10-02 16:14
Hi Bouwe, 

I have installed the update.  with heating I do indeed have auto and heating.  when i switch on cooling i have cooling and auto.  both heating and cooling function well!  I assume the Auto feature is on a schedule?  I haven't tested this yet.

the dhw modes do not function correctly yet.  the mode which is active by on the heat pump is displayed, however it is not possible to switch to another mode.  see the print screen for this.  setting maximum water temperature is working properly.  I can't find the current water temperature (boiler) yet?![image](https://user-images.githubusercontent.com/102429191/193464522-e0cbaddb-a119-4f38-bfc6-0aef1b7c2d72.jpeg)

so much progress has already been made👌

**Comment by bouwew** [comment] 2022-10-02 16:43
@Wishdoc Thanks for the feedback, there is good progress I see :)

Regarding the select error, is there any detailed information in the LOGBOEK that can help me to find the cause of the error?

**Comment by Wishdoc** [comment] 2022-10-02 16:55
Out of the logfile:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/plugwise/select.py:129 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 16:00:42 (17 occurrences) 
Last logged: 18:53:04

[547056218752]
[547005046432]
[547004573888]
[547274508752]
[546871708160]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 54, in async_select_option
    await entity.async_select_option(option)
  File "/config/custom_components/plugwise/select.py", line 129, in async_select_option
    await self.entity_description.command(
  File "/usr/local/lib/python3.10/site-packages/plugwise/smile.py", line 797, in set_dhw_mode
    await self._request(uri, method="put", data=data)
  File "/usr/local/lib/python3.10/site-packages/plugwise/helper.py", line 301, in _request
    return await self._request_validate(resp, method)
  File "/usr/local/lib/python3.10/site-packages/plugwise/helper.py", line 252, in _request_validate
    raise ResponseError
plugwise.exceptions.ResponseError

**Comment by Wishdoc** [comment] 2022-10-02 16:55
Deze fout is ontstaan door een aangepaste integratie.

Logger: plugwise.constants
Source: custom_components/plugwise/select.py:129 
Integration: Plugwise Beta (documentation) 
First occurred: 16:00:42 (17 occurrences) 
Last logged: 18:53:04

Smile response empty or error in <?xml version="1.0" encoding="UTF-8"?> <error> <code>400 Bad Request</code> <message>Resource path for URI &apos;/appliances;id=bfb5ee0a88e14e5f97bfa725a760cc49/actuator_functionalities/domestic_hot_water_mode_control_functionality&apos; is invalid: &apos;actuator_functionalities&apos; not expected at position 3.</message> </error>

**Comment by Wishdoc** [comment] 2022-10-02 16:56
Logger: frontend.js.latest.202209072
Source: components/system_log/__init__.py:227 
First occurred: 15:27:33 (11 occurrences) 
Last logged: 18:53:11

:0:0 Script error.

**Comment by Wishdoc** [comment] 2022-10-02 16:57
the functionality was still disabled after the update.  it manually enabled and updated.

**Comment by bouwew** [comment] 2022-10-02 17:29
Ah yes, now I remember, I was not sure about the exact data to put in the PUT/POST-request the is part of the select-option.

Are you able to capture http-traffic using Wireshark or some similar software?

**Comment by Wishdoc** [comment] 2022-10-02 17:54
Just installed wireshark. If you can tell me what to do.

**Comment by bouwew** [comment] 2022-10-02 18:04
Ok great.

1) Configure Wireshark for the correct wired or wireless interface
2) Open the Anna website in a browser: http://<anna_ip_address>
3) Find in Instellingen when you can change the DHW-mode
4) Start Wireshark, you should already see traffic-messages pass by in the Wireshark window.
5) Change the DHW-mode and press Save
6) Stop the caputuring of Wireshark.
7) Find the corresponding line, it should be a PUT or a POST command.

I see this when I change the regulation-mode on my Adam:
![image](https://user-images.githubusercontent.com/11290930/193468943-9e0efce5-bd84-4dda-9b5f-e47af4a6daa7.png)

Double-click on that line, a separate window opens.
Press on the + in front of the line Hypertext Transfer Protocol, I'm interested in the 1st line below the line Hypertext Transfer Protocol, what does it show?

**Comment by Wishdoc** [comment] 2022-10-02 18:55
this is a PUT line 
![image](https://user-images.githubusercontent.com/102429191/193471052-976d4b28-9313-4179-beed-fad2603e6d2f.png)



PUT /core/appliances;type=heater_central/domestic_hot_water_mode_control HTTP/1.1\r\n

**Comment by bouwew** [comment] 2022-10-03 06:10
Thanks!

Please update to v0.30.0a2 and report back.

**Comment by bouwew** [comment] 2022-10-03 13:40
"I assume the Auto feature is on a schedule?": Yes, auto means in HA climate that for instance a schedule with various setpoints that change at certain times, is managing the heating/cooling operation. Verwarmen/koelen means there's no schedule active. It means the heating/cooling is based on a fixed setpoint.

"I can't find the current water temperature (boiler) yet?": I think you mean the domestic hot water temperature? This one would be a new sensor that I haven't seen before. I see the corresponding xml-key in the provided data, adding this sensor should be quick.

**Comment by Wishdoc** [comment] 2022-10-03 14:05
> Thanks!
> 
> 
> 
> Please update to v0.30.0a2 and report back.

Hi Bouwe, 

the dhw works very well.  awesome

**Comment by bouwew** [comment] 2022-10-03 14:07
Nice, good to hear :)
I'll add the missing sensor tonight.

**Comment by Wishdoc** [comment] 2022-10-03 14:14
> "I assume the Auto feature is on a schedule?": Yes, auto means in HA climate that for instance a schedule with various setpoints that change at certain times, is managing the heating/cooling operation. Verwarmen/koelen means there's no schedule active. It means the heating/cooling is based on a fixed setpoint.
> 
> 
> 
> "I can't find the current water temperature (boiler) yet?": I think you mean the domestic hot water temperature? This one would be a new sensor that I haven't seen before. I see the corresponding xml-key in the provided data, adding this sensor should be quick.
> 
> 

Yes it's the DHW temperature.

**Comment by bouwew** [comment] 2022-10-03 17:28
Please update to v0.30.0a3, the Opentherm DHW Temperature sensor has been added.

**Comment by Wishdoc** [comment] 2022-10-04 06:40
This is indeed the sensor I'm talking about.  functions perfectly.  thanks

**Comment by Wishdoc** [comment] 2022-10-04 08:17
Now I'll try to automate some stings like use the solar energy to heat the dhw.

**Comment by bouwew** [comment] 2022-10-04 08:59
> This is indeed the sensor I'm talking about. functions perfectly. thanks

Great, so now everything is working as intended?

I still need to make some changes to the plugwise-backend (I think), related to other types of systems. So there will be one or two more alpha releases that I might ask you to test.
When that's all done I'll make a formal v0.30.0 release.

**Comment by bouwew** [comment] 2022-10-04 11:54
The reading frequency of the dhw-temp is first determined by the Plugwise software in the Smile.
Also, you can change the update-interval of the plugwise-beta integration in HA. It is as a default set to 60 seconds.
Via the CONFIGUREER button in the integration tile you can change that interval to for instance 30 seconds.

**Comment by Wishdoc** [comment] 2022-10-04 20:14
Ok thanks, I'll try

**Comment by bouwew** [comment] 2022-10-05 05:39
Implemented via #304

**Comment by bouwew** [comment] 2022-10-08 09:34
Released in v0.30.0

**Comment by bouwew** [comment] 2022-10-15 08:05
@Wishdoc I have put pw-beta v0.31.0a0 online, as a pre/beta release.
Can you please test this version?

What has been changed is how heating and cooling is represented: with this version the climate card will show two setpoints, the heating-setpoint and the cooling-setpoint. I know, this is not how Plugwise represents this but this is how Home Assistant Core represents it. And I cannot deviate from that in the HA Core Plugwise Integration. And we want to keep Plugwise-beta mostly the same as HA Core Plugwise.

Please note: when changing the cooling setpoint in HA when in heating mode, and vice versa, you will see an error.

**Comment by Wishdoc** [comment] 2022-10-15 15:02
I will update now, I'll let you know the findings

**Comment by Wishdoc** [comment] 2022-10-15 15:47
![image](https://user-images.githubusercontent.com/102429191/195995277-5479606e-fbc0-4de0-8c3f-bbe238a801a3.png)

Hi Bouwe, something is wrong with setting the temperature.  when I want to adjust the heating temperature during heating I get an error message, and when I adjust the cooling temp no error.  so something seems wrong
By cooling the same problem.

Hans

**Comment by bouwew** [comment] 2022-10-15 18:28
Ok thanks. I'll have a look at what could be wronf.
Is there any extra information in the LOGBOEK available?

**Comment by bouwew** [comment] 2022-10-15 18:54
I'm not sure why this happens. But I made a small change in v0.31.0a1. Please install and test.
Does that change help?

**Comment by bouwew** [comment] 2022-10-15 18:57
Wait, I suddenly see in a picture that you posted, what is wrong.
I will try to fix this tomorrowmorning.

**Comment by Wishdoc** [comment] 2022-10-15 19:00
OkAy, for now I will install v0.30.0

**Comment by bouwew** [comment] 2022-10-16 08:20
@Wishdoc v0.31.0a2 is available for testing.

**Comment by Wishdoc** [comment] 2022-10-16 08:34
Later this day I'll try.

**Comment by Wishdoc** [comment] 2022-10-16 09:07
Just installed, a quick check:

- heating looks ok.

- cooling modus, 

The desired temperature cannot be set via cooling, but via heating.  also the setpoint temperature is displayed in “Anna heating setpoint "

**Comment by bouwew** [comment] 2022-10-16 09:18
Nice! 

Yes, the cooling-setpoint cannot change when the system is in heating-mode. And vice versa in the cooling-mode.
The way the Plugwise software works, does not really support that. We could probably create some kind of work-around. Or show a warning on the screen.

**Comment by bouwew** [comment] 2022-10-16 09:24
With the above information, does this mean that the bug is solved?

**Comment by Wishdoc** [comment] 2022-10-16 12:36
No, the problem I meant, is already in cooling mode.

**Comment by bouwew** [comment] 2022-10-16 17:04
Ok I see what you mean. Apparently the heating-setpoint becomes the cooling-setpoint when you enable cooling and there is no schedule active. Does the cooling become active with this setpoint?

**Comment by Wishdoc** [comment] 2022-10-16 17:18
As far as I see in the plugwise app. It would be activated. But the outside temperature is to cold now for activating. I will try tomorrow.

**Comment by bouwew** [comment] 2022-10-16 17:20
Ah Ok so that's how you avoid the cooling from becoming active.

Anyway, the problem is clear. I'll rework the code to make it work like shown in the Plugwise App.

**Comment by Wishdoc** [comment] 2022-10-17 13:30
tested again today.  when the cooling is switched on nothing changes on the hass thermostat.  when cooling becomes active, the thermostat with the values ​​also changes as you expect![image](https://user-images.githubusercontent.com/102429191/196189199-ceb94c37-b59d-439c-9dfe-ea536bdca1f6.jpeg)

how do i interpret the high and low temperature of the thermostat.  with cooling the "highest" temperature is leading I see and with heating the "lowest" temperature.  what is the function of the other temperature that can be set?

**Comment by Wishdoc** [comment] 2022-10-17 15:47
I meant the 4 degrees( heating setpoint). I didn't see the advantage of it. 
As I understand in the next update this will be one temperature.

**Comment by bouwew** [comment] 2022-10-17 18:07
Please install and test v0.31.0a5.

Without an active schedule the heating- and cooling-setpoints should be equal.
If there is a schedule active then the setpoints will already switch when the cooling function is enabled/disabled. 
And not when cooling/heating becomes active.

**Comment by Wishdoc** [comment] 2022-10-17 19:16
temperature is almost impossible to adjust.  There seem to be 2 setpoints that don't "slide" together.  attached 2 print screens.  1 where the 2 set temperatures are visible (only then can the temperature be adjusted) then the “globules” go together again and adjusting is not easy to do![image](https://user-images.githubusercontent.com/102429191/196263177-2f7cec65-71d4-489e-98ee-085f3d002432.png)![image](https://user-images.githubusercontent.com/102429191/196263232-fa313f43-3968-4163-9934-b002ed5641b6.png)

**Comment by bouwew** [comment] 2022-10-20 18:08
Assumed fixed by v0.31.0.
To cold already to test in cooling mode.

**Comment by Wishdoc** [comment] 2022-10-27 16:25
Today was a great day to test te cooling feature. And as expected it works fine. Great job @bouwew

**Comment by bouwew** [comment] 2022-10-28 11:42
Nice! Thanks for your help in testing :)

**Comment by Wishdoc** [comment] 2023-05-21 14:53
Hallo Bouwe,

Eind vorig jaar heb je me via github geholpen met de integratie voor de anna / plugwise integratie icm loria Duo .

Inmiddels zijn we een paar maanden verder en wou ik vandaag de koeling eens weer proberen.  Tot mijn verbazing functioneerde het niet helemaal correct. De app bijgewerkt naar de nieuwste versie en functioneert nu/nog niet ( meer ).

Zoals op mijn printscreen te zien zijn er een aantal entiteiten niet meer beschikbaar.
Waaronder Cooling ( aan/uit ) , setpoint Heating, setpoint Cooling en DHW setpoint.

Heb jij nog een keertje zin en tijd om hierin te duiken zodat het weer functioneert?

Hoor graag van je,

Mvg Hans Mengerink

***@***.***

***@***.***


Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: Bouwe ***@***.***>
Verzonden: vrijdag 28 oktober 2022 13:42
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [plugwise/plugwise-beta] Plugwise features loria extra entities (Issue #301)


Nice! Thanks for your help in testing :)

**Comment by bouwew** [comment] 2023-05-22 06:18
@Wishdoc Ja, dat zou heel goed kunnen, er is inmiddels flink wat aangepast mbt de koelfunctie.
En er zijn ook andere aanpassingen gemaakt, zoals benamingen en vertalingen. Kan het zijn dat de namen veranderd zijn?

En, ik zie geen printscreen? Graag rechtstreeks in het github-Issue posten :)

**Comment by Wishdoc** [comment] 2023-05-24 06:38
here are the images.
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/76102c03-47b3-4704-8695-92e9bcd09611)

![image](https://github.com/plugwise/plugwise-beta/assets/102429191/a57214f0-1901-4f4a-a4df-0a8b27fabd29)

![image](https://github.com/plugwise/plugwise-beta/assets/102429191/5b7488ef-6058-4d65-b95a-e5a582207780)

Also when manual cooling is enabled, adjusting the target temperature does not work either. it goes right back to the original setting.

**Comment by bouwew** [comment] 2023-05-24 12:50
Please upload the diagnostics file.

**Comment by Wishdoc** [comment] 2023-05-25 10:56
Here are the diagnostics from the integration

[config_entry-plugwise-e0b2139cd4379e81c2e59660651ec5dc.json.txt](https://github.com/plugwise/plugwise-beta/files/11563971/config_entry-plugwise-e0b2139cd4379e81c2e59660651ec5dc.json.txt)

**Comment by bouwew** [comment] 2023-05-25 11:46
When I look at the data in the diagnostics-file, everything is there:
```
        "switches": {
          "cooling_ena_switch": false,

        "sensors": {
          "...."
          "setpoint_low": 10.0,
          "setpoint_high": 30.0
```

So it looks like the data received from the backed library contains the required data-points.

Are there any Plugwise-related errors in the HA Core LOGBOEK?

**Comment by Wishdoc** [comment] 2023-05-26 08:15
I'll place the logfile here. Yesterday 22:11 the wifi had a reset with a lot of errors in the log. 
[home-assistant_2023-05-26T07-31-37.867Z.log](https://github.com/plugwise/plugwise-beta/files/11573002/home-assistant_2023-05-26T07-31-37.867Z.log)

**Comment by bouwew** [comment] 2023-05-26 08:29
Thanks. There are plugwise-related errors in the logfile but these are caused by the fact that the network connection is not there.

You might need to remove the Plugwise integration, restart HA and then re-add the Plugwise integration, that should restore the missing sensors, etc.

**Comment by Wishdoc** [comment] 2023-05-26 08:32
I'll give it a try.

**Comment by Wishdoc** [comment] 2023-05-26 08:53
Now i got only 1 device and 19 entities, before i had 3 devices in the integration.  Now also al lot of "lost entities"

Is this because something went wrong. or because of the changes in the integration?

![image](https://github.com/plugwise/plugwise-beta/assets/102429191/f4ed77e8-71f8-4208-8672-882bb1c78201)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/c4d22232-95d5-4f81-bfaf-3fbd79220ea4)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/200cf1ac-29a7-434e-85a4-4b4de9ff3fd4)

**Comment by bouwew** [comment] 2023-05-26 09:54
We added translations recently so it might be that the various sensor names etc. have changed.
Are these your own created visuals?

Please look at Instellingen --> Apparaten & Diensten --> Plugwise Smile/Stretch Beta --> Anna
There should be all the devices and entities visible with their present names.

**Comment by bouwew** [comment] 2023-05-26 10:10
That you see 1 device and not more is something of HA, wait a little time, then it should show the expected amount of devices.

**Comment by Wishdoc** [comment] 2023-05-28 05:33
> Are these your own created visuals?

These are my own screenshots of my dashboard.  Unfortunately I have yet to fix the automations 

I have now linked the translated entities back to my dashboard. But the same entities  as we started are still lost.  :-( 
So it still is nog possible to activate cooling.  and set temperature for cooling ( after manually activate cooling at the heatpump) .  Even some other entities are lost.

**Comment by bouwew** [comment] 2023-05-28 06:57
Can you show me screenshots of what you see at Instellingen --> Apparaten & Diensten --> Plugwise Smile/Stretch Beta --> Anna?

**Comment by Wishdoc** [comment] 2023-05-28 07:06
sure no problem. but at the moment i'm restoring an older back-up. to check something. Afterwards i'll restore my current configuration and place the screenshots as well as the diagnostics.

thanks so far

**Comment by Wishdoc** [comment] 2023-05-28 07:28
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/96188aac-4400-428a-91df-31131b1472a3)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/047cfa5c-c07c-41e5-b4f2-dd05404b3670)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/c2bf564e-b069-41a4-b2bd-457c3ca2092a)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/e8eeb6af-418a-45b0-9106-8a5aad97bc68)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/85871954-0377-430a-8d21-911a52282d47)

"Also, if you have followed my advice and removed an added the plugwise-beta integration, please attach a new diagnostics-file." 

ofcourse i did, after that all the names of the entities have been changed. 

_"Now i got only 1 device and 19 entities, before i had 3 devices in the integration. Now also al lot of "lost entities"

Is this because something went wrong. or because of the changes in the integration?"_

**Comment by bouwew** [comment] 2023-05-28 07:58
Can you send me a new diagnostics file? 
Maybe that will show me now what has changed. I do see that the cooling/heating-setpoints are missing, as is the cooling-switch.

"1 device and 19 entities", I have that too, it something that HA does. When you look a few minutes later, the numbers will be correct.

**Comment by Wishdoc** [comment] 2023-05-28 08:04
sorry, maybe it's a little confusing. The previous is actual. ( NEW)  restore update didn't go well.  before i had 3 devices 23 entities. Now 3 devices en 19 entieties. 

here is the new diagnostic
[config_entry-plugwise-6b9c8b71017b94846faee919f3ae63d5.json.txt](https://github.com/plugwise/plugwise-beta/files/11584007/config_entry-plugwise-6b9c8b71017b94846faee919f3ae63d5.json.txt)

**Comment by bouwew** [comment] 2023-05-28 08:24
Thanks.

All devices are there in the diagnostics file, also the missing ones in the dashboard.

Very strange.
The strange thing is, in my HA translations to NL mostly don't work. But in your system they do seem to work, at least more/better than in my system.

Can you check something for me: please look at Ontwikkelhulpmiddelen --> Statussen, in Filter entiteiten search for `instelling`, do you see any sensors what that word in the name? If not, search for `setpoint`, do you now see any sensors what that word in the name?

**Comment by Wishdoc** [comment] 2023-05-28 08:37
Instelling and setpoint both nothing present

![image](https://github.com/plugwise/plugwise-beta/assets/102429191/298a7497-03af-48d8-b024-f80b046bd320)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/1d161428-6d5e-4b61-ac0d-dfc98815929b)

**Comment by bouwew** [comment] 2023-05-28 08:47
Ok, very strange.

Can you try something?
Delete the plugwise integration, in HACS, plugwise integration, select `opnieuw downloaden`, turn `show beta` off, then install version v0.34.9.
Next, restart HA, then install the plugwise integration again. Do you now see the missing sensors again?
You should see them, v0.34.9 is the last version before adding the sensor/switch/etc. name-translations.

And, if you then upgrade to v0.40.3.a1, what do you see then after the upgrade?

**Comment by Wishdoc** [comment] 2023-05-28 08:53
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/991b16c3-ae61-4078-b75d-132b68c6c26e)
version V0.34.9 is not available. try to install v0.40.2 ? and then 0.40.3.a1?

![image](https://github.com/plugwise/plugwise-beta/assets/102429191/b37d1d8d-27a0-4692-bf17-8d0180428238)

**Comment by bouwew** [comment] 2023-05-28 09:01
Please follow the instructions: turn off `Betaversies weergeven`, you might need to close this window an reopen it again for the change to have effect.

**Comment by Wishdoc** [comment] 2023-05-28 12:01
version v.0.34.9  the  missing  entities are back. 
adjusting temperature in cooling mode is not possible. ( can change the temp but falls back to original temp )
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/ee973c73-f524-4194-bfa5-ede42484302a)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/c2f6bd29-46cb-40dc-ac4e-47381b4693bc)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/9f01ed56-0393-4c90-a1c0-02047faa859f)

**Comment by Wishdoc** [comment] 2023-05-28 12:20
after update v0.40.3.a1
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/7071bc7c-85ad-410c-8ee6-f427a4050c44)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/6c14bed2-258b-42b7-839f-1250091585f2)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/14b72843-a6ec-4306-a45c-e71dd929cbc0)


there is also info available at Ontwikkelhulpmiddelen

![image](https://github.com/plugwise/plugwise-beta/assets/102429191/fc48fe69-e477-4d39-bd6d-fbcefb77c754)

The enitities are lost again

**Comment by bouwew** [comment] 2023-05-29 14:45
What happens when you set the HA language to English and then restart HA, do the missing sensors-etc. then show up?

**Comment by Wishdoc** [comment] 2023-05-30 12:04
at the moment (I think) all entities are functioning well. version v.0.34.9 with my backup before the translation came in.

during cooling it is difficult to set the desired temperature. see video. cooling is active at the beginning and the desired temperature for heating can be set, but not cooling. then cool ln turns off and the exact same thing happens.

https://github.com/plugwise/plugwise-beta/assets/102429191/c6413fec-49b0-4073-9150-3b021435e9f1

**Comment by bouwew** [comment] 2023-05-30 16:23
Agree, you should stay at v0.34.9 until we have a better idea why the name-translations don't work as intended.

I'll have a look at the code to try finding out why changing of the setpoint does not work for cooling.

**Comment by Wishdoc** [comment] 2023-05-30 16:58
if it is necessary to test it with HA to the English language, I am willing to do so. Otherwise i'll keep version v0.34.9

**Comment by bouwew** [comment] 2023-05-30 17:33
No, not needed to test with English language.

**Comment by bouwew** [comment] 2023-06-03 10:55
@Wishdoc can you please install and test version 0.34.11a0?

I discovered a bug in the `set_temperature()` function, this has been fixed. Now changing the cooling-setpoint, when in cooling mode, and changing the heating-setpoint, when in heating mode, should work correctly.

Please note: changing the cooling-setpoint, when in heating mode, and changing the heating-setpoint, when in cooling mode is not possible, Plugwise does not allow for that. I have implemented that the code raises an Error, I'm not sure if that error will be visible in HA.

Finally, on the climate-card, only the active setpoint and the min or max value for the "non-active setpoint" is shown. The values that are in the active schedule for the "non-active setpoint" are now ignored.

**Comment by Wishdoc** [comment] 2023-06-04 08:38
@bouwew just installed and tested. Adjusting the temperature is not possible.
See screenshot out of "logboek".  
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/1af03df4-6cec-4af4-ae46-7c51a9c8f5e7)

also "volledig logboek" attached.
[home-assistant_2023-06-04T08-17-53.901Z.log](https://github.com/plugwise/plugwise-beta/files/11645174/home-assistant_2023-06-04T08-17-53.901Z.log)


and "diagnostiek" out of integration attached.
[config_entry-plugwise-e0b2139cd4379e81c2e59660651ec5dc.json (1).txt](https://github.com/plugwise/plugwise-beta/files/11645177/config_entry-plugwise-e0b2139cd4379e81c2e59660651ec5dc.json.1.txt)

**Comment by Wishdoc** [comment] 2023-06-04 08:40
@bouwew 

For now, after activating and deactivating cooling mode it's not possible to re-activate the cooling mode. 


Dispite to cooling mode is not active  the following error appears.
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/6eb4f416-2d95-4952-bb1f-466e82b4443d)

**Comment by bouwew** [comment] 2023-06-04 11:06
Please install pw-beta v0.34.11a1, with this version the setpoint_high/-low values should be correct.
Please test again and let me know your results.

**Comment by Wishdoc** [comment] 2023-06-04 12:42
@bouwew https://github.com/plugwise/plugwise-beta/assets/102429191/82381d2d-ff0c-44a7-93a2-c9bce752294a

When it is in heat mode, it looks like he's expecting Plugwise is in cooling mode and vice versa

**Comment by Wishdoc** [comment] 2023-06-04 13:10
Both ways gave problems. 

In this video I only changed the highest temperature in cooling mode. And only change the lowest temp in heating mode. Also after manually changing the cooling switch it changes automatically off and on again and vice versa 

Only looked in Plugwise app to see if cooling really is activated. ( no manual action in Plugwise app )

https://github.com/plugwise/plugwise-beta/assets/102429191/5a278107-c980-4250-8635-90249159e0d5

**Comment by bouwew** [comment] 2023-06-04 17:43
@Wishdoc Ok, hopefully more bugs fixed: please try v0.34.11a2

**Comment by Wishdoc** [comment] 2023-06-05 09:59
Installed v0.34.11a2

When in heating mode changing the lowest setpoint this error appears
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/4952f6ae-4c2f-4d61-a13e-a80aae66c812)




When in cooling mode changing the highest setpoint the following error appears. 

![image](https://github.com/plugwise/plugwise-beta/assets/102429191/4688e3b8-1638-4249-a786-69c30ad5c878)

**Comment by bouwew** [comment] 2023-06-05 10:11
Again, thanks for testing.
There is still something in reverse I think.
How do the climate-cards look like when the system is in heating-mode, and in cooling mode?

In heating mode the low (left) setpoint should show the heating-setpoint, the high (right) setpoint should be at 30°C.
In cooling mode the low (left) setpoint should be at 4°C, the high (right) setpoint should show the cooling-setpoint.

**Comment by Wishdoc** [comment] 2023-06-05 10:32
Looks like you described. 
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/9778c1cc-5edf-45c5-907d-df2c80ae8060)
![image](https://github.com/plugwise/plugwise-beta/assets/102429191/1d70b564-fb78-4cf2-817b-de1cbe335575)

**Comment by bouwew** [comment] 2023-06-05 13:28
Very good to know that this at least functions as intended, thanks!
Tonight I'll think about what causes the error-messages.

**Comment by bouwew** [comment] 2023-06-05 16:57
@Wishdoc please test v0.34.11a4

**Comment by Wishdoc** [comment] 2023-06-06 09:45
@bouwew 

first tests seems good. Later today I'll take a closer look.

**Comment by Wishdoc** [comment] 2023-06-06 20:49
@bouwew 

Hi Bouwe,

everything seems to be working fine. you did great again.

Thanks

**Comment by bouwew** [comment] 2023-06-07 06:01
@Wishdoc thanks for testing, I'm happy all is working :slightly_smiling_face:

**Closed by bouwew** 2023-06-07 06:01 UTC
Labels: enhancement

**Comment by bouwew** [comment] 2023-06-13 07:29
@Wishdoc we released Plugwise-beta v0.40.3 just now.

I would appreciate it if you could install this version and test it.
If you still see missing entities, please create a new Issue for this problem.
Also, please check the Home Assistant LOGBOEK for any plugwise-related errors.
If these are not there, please enable debugging for the Plugwise integration, restart HA and then send me a logfile.

**Comment by Wishdoc** [comment] 2023-06-19 18:10
Hi Bouwe, sorry for the late response. a lot of things have happened lately that make me forget about this.

Probably Wednesday I'll have time to test it out.

**Comment by Wishdoc** [comment] 2023-06-21 19:25
@bouwew I created a new issue
