### ISSUE TITLE
Anna v1.8.20 not working

### ISSUE THREAD

**Issue by sanderdw** [plugwise/plugwise-beta#11] opened 2020-04-02 10:07 UTC
As requested by @bouwew (https://github.com/home-assistant/core/issues/28947#issuecomment-607419232) i installed the new plugwise-beta component in my clean home assistant test setup.

Plugwise Anna version: v1.8.20 (so the old version)

**Installing:**
Adding this Repo to HACS went fine and also adding the integration was easy. Maybe you could document it somewhat clearer that you have to add this git repo to HACS, but i figured it out anyway.

After adding the integration it's also added to Lovelace:
![image](https://user-images.githubusercontent.com/19476345/78235984-b0228900-74d9-11ea-9cf8-1f816830b6d5.png)

But it is a water_heater instead of a climate component?
![image](https://user-images.githubusercontent.com/19476345/78236213-fb3c9c00-74d9-11ea-8549-9a7c2d4d375f.png)

This are the entity's that were added by this component:
![image](https://user-images.githubusercontent.com/19476345/78236546-6be3b880-74da-11ea-8f27-7b0914f97c5c.png)

Also the reported temperature (33) is not correct. Currently it's 20.1 and climate is set to 20. So it's seems it's reporting the boiler temperature in the first screenshot.
[direct_objects.zip](https://github.com/plugwise/plugwise-beta/files/4420291/direct_objects.zip)

Let me know what to check next?

Thanks for developing this nice component!

**Comment by CoMPaTech** [comment] 2020-04-02 10:28
@sanderdw Those values should be from your water-heater/boiler. Looks like something doesn't match up in our code to add the 'climate' part. (Or better stated, to detect which one is your climate).

We are patching up to 0.0.51 but I don't think that will ensure your climate will be detected (there are minor fixes in there for Anna 1.8, but I don't suppose it will fix this).

**Comment by bouwew** [comment] 2020-04-02 10:31
@sanderdw can you show us the errors related to plugwise-beta in Developer Tools --> Logs?

**Comment by bouwew** [comment] 2020-04-02 10:34
The temperature reported by the water_heater is the temperature of the water inside your CV-ketel. The water_heater represents the CV-ketel and shows it operating state: idle, heating or hot_water.
Each state also has it's own appropriate icon.

**Comment by sanderdw** [comment] 2020-04-02 11:18
Here is a sceenshot of the log:
![image](https://user-images.githubusercontent.com/19476345/78243631-64291180-74e4-11ea-95e2-77d68b6f2b2e.png)

Not much info...

**Comment by bouwew** [comment] 2020-04-02 11:19
Ok, no error, thanks.

**Comment by bouwew** [comment] 2020-04-02 11:37
The next release should fix the missing climate-entity. Coming soon...

**Comment by bouwew** [comment] 2020-04-02 11:45
Graag naar versie 0.0.52 updaten en HA herstarten.

**Comment by sanderdw** [comment] 2020-04-02 12:03
Updated and did a fresh intergration again:
![image](https://user-images.githubusercontent.com/19476345/78247015-64c4a680-74ea-11ea-9917-0624ec0c04fa.png)

anna_temperature = 20.09 and anna_thermostat = 20.0 are correct. Not seeing a climate component yet though...

**Comment by bouwew** [comment] 2020-04-02 12:08
Can you please enable the logger in configuration.yaml?
```
logger:
  default: warn
  logs:
    custom_components.plugwise-beta: debug
```
And then restart HA once more?

After the restart go to Developer Tools --> Logs and press the large refresh HA Log below the separation-line.There should be many lines related to plugwise-beta, please show us these.

**Comment by sanderdw** [comment] 2020-04-02 12:19
![image](https://user-images.githubusercontent.com/19476345/78248475-fd5c2600-74ec-11ea-8393-37552cf50548.png)

**Comment by bouwew** [comment] 2020-04-02 12:20
Great, thanks, this helps.

**Comment by CoMPaTech** [comment] 2020-04-02 14:58
Just pushed out 0.0.54 #13 that should fix this

**Comment by sanderdw** [comment] 2020-04-02 15:06
![image](https://user-images.githubusercontent.com/19476345/78265074-423f8700-7504-11ea-9a98-23c4b0fd916c.png)

**Comment by bouwew** [comment] 2020-04-02 15:19
That is progress!
Yes, I noticed that too, the Anna says heating and the water_heater says hot_water.
What kind of device do you control with the Anna? And is it creating hot water?

**Comment by sanderdw** [comment] 2020-04-02 15:25
It's a vaillaint boiler. The 'native' integration is reporting it correctly.

I turned on the heating to see what it shows but it makes no difference.

**Comment by bouwew** [comment] 2020-04-02 15:28
Can you please capture the /core/appliances XML-data with heating on and heating off?

**Comment by bouwew** [comment] 2020-04-02 15:29
Also, do you see a difference on the Anna when the heating is on versus when hot water is being tapped?

**Comment by sanderdw** [comment] 2020-04-02 15:45
Ok so i got the xml files when not heating, using the central heating and also tapping hot water:
[anna_status.zip](https://github.com/plugwise/plugwise-beta/files/4422063/anna_status.zip)

**Comment by bouwew** [comment] 2020-04-02 15:53
Thanks!

Looks like domestic_hot_water_state is always on,
central_heating_state is always off,
and boiler_state is on when heating or tapping hot water, otherwise off. So only boiler_state to look at in your system.

**Comment by bouwew** [comment] 2020-04-02 15:56
Ah yes, in haanna it reads: 
```
    def get_domestic_hot_water_status(self, root):
        """Get the domestic hot water status."""
        if self.legacy_anna:
            return None
```
And we do not do that (yet) in Plugwise-Smile.

**Comment by bouwew** [comment] 2020-04-02 16:43
Please try release 0.0.55. Now the heating-result should be the same as the native component.

**Comment by sanderdw** [comment] 2020-04-02 17:20
Updated: it still says heating when it's not:
![Screenshot_20200402-191913](https://user-images.githubusercontent.com/19476345/78278856-f518e080-7516-11ea-84be-e9ff1d67b0d5.jpg)

**Comment by bouwew** [comment] 2020-04-02 17:42
Ok, good, issue solved :)

About the picture, the flame icon actually means there is no schedule active, it is in standard heating-mode following the setpoint that can be changed manually, from within HA, the Pw App or from the Anna.
If you create a week-schedule in the Plugwise App and activate it there, in HA the schedule-icon would turn green together with the circle, indicating it is in auto-mode, with an "AI" regulating the setpoint.
Also, please know that the status shown with the circle is not the function of the CV-ketel, it is simply showing: no heating required == inactief, or heating required = verwarmen. The algo is very simpel: `if current_temp < heating_setpoint then need heating`, etc. The true status of your CV-ketel is shown by the water-heater-entity.
The reason to do it like this is coming from the Adam to which many thermostats can be connected. In the old situation they would all show the same status while the heating-demand would only come from one thermostat. With the new algo it is clear which thermostat has a heating-demand.

Our last request: can you please create a weekschedule and test if you can activate it and deactivate it from within HA?

**Comment by sanderdw** [comment] 2020-04-02 18:18
I'm not sure if I understand you correctly. According to me the active flame should only be there when either the central heating is active or when you are tapping hot water, right? 

Wil check the schedule stuff tomorrow, thanks for helping!

**Comment by bouwew** [comment] 2020-04-02 18:33
Incorrect, the orange flame- or the green schedule-icon are always there/on, when selected, because they show the active climate MODE. What you are looking for is the active climate ACTION which is shown via the text (Inactief, etc.). See here for details: https://developers.home-assistant.io/docs/entity_climate/
There can also be a cooling-icon or an off-icon, representing other HVAC-MODES.

Many people think like you but you are thinking wrong. Ask the top-HA guys, they will tell you the same, they have come up with the present, maybe illogical, implementation.

**Comment by bouwew** [comment] 2020-04-03 14:52
Closing this topic as the issue is solved.

**Comment by bouwew** [comment] 2020-05-07 15:43
@sanderdw Do you see an icon of a tap on the screen of your Anna when you are tapping hot water?

**Comment by bouwew** [comment] 2020-05-07 16:04
Yes, on the screen of the Anna itself.
Ok, good to know, then our assumption that the legacy Anna did not support showing this state/icon is wrong. Now we need to find out why on one user's legacy Anna the key "domestic_hot_water_state" is always "on", whether he is tapping hot water or not...

**Comment by bouwew** [comment] 2020-05-08 06:27
@sanderdw, please update to version 0.2.4rc0 and let me know if on climate.anna(?) hvac_mode is showing the heating and idle states correctly and if binary_sensor.auxiliary_dhw_state is showing the state of tapping hot water correctly.

**Comment by sanderdw** [comment] 2020-05-08 07:20
How can i install this version with HACS? 0.2.3 is reported as the last version.

**Comment by CoMPaTech** [comment] 2020-05-08 07:21
`You can make this version visible in HACS, when you are in the selected Plugwise-beta integration, by clicking the 3 dots on the right and selecting "Show beta".`

**Comment by sanderdw** [comment] 2020-05-08 10:18
[0.2.4rc0.xlsx](https://github.com/plugwise/plugwise-beta/files/4598399/0.2.4rc0.xlsx)

Here you go. I included everything, also the core 'legacy' implemantion.

**Comment by bouwew** [comment] 2020-05-08 11:30
@sanderdw, I see two test-cases: everything off and heating tap-water. Can you also please test the case of heating the radiators/floor?
What I am seeing for the two test-case, all looks OK.

About the difference between the present and legacy implementation, "hvac_mode" is not a representation of the heater-state, this state is provided by "hvac_action". "Hvac_mode" shows the operation-mode of the system: either auto-mode or heat-mode. Auto-mode means controlled by an automation like a weekly schedule, heat-mode means, set to heating based on a fixed setpoint (which can only be changed "manually"). I think they should give this mode another name :)
Please note, the legacy-implementation was not according to the HA-climate-guidelines.

**Comment by sanderdw** [comment] 2020-05-08 13:30
[0.2.4rc0_v2.xlsx](https://github.com/plugwise/plugwise-beta/files/4599198/0.2.4rc0_v2.xlsx)

I updated the sheet with the heating turned on.

Yes, about these guidelines, iagree to follow them even it's a little weird :). Thanks anyway.

**Comment by bouwew** [comment] 2020-05-09 08:10
@sanderdw version 0.2.4rc1 is available on HACS, please test.

**Comment by sanderdw** [comment] 2020-05-11 16:04
[0.2.4rc1.xlsx](https://github.com/plugwise/plugwise-beta/files/4610704/0.2.4rc1.xlsx)

Will add heating the water later...

**Comment by bouwew** [comment] 2020-05-11 17:28
Thanks. Another user told me too that it doesn't work. He is checking a possible solution for me. And I have asked for help from Plugwise. More to follow...

**Comment by sanderdw** [comment] 2020-05-18 09:23
Hi @bouwew just wanted to let you know that i installed 0.2.9rc0 and now the integration is broken. I also tried to re-add the integration but none if the devices and entity's are showing anymore.

**Comment by bouwew** [comment] 2020-05-18 09:27
@sanderdw Sorry to hear that. What is shown in Developer Tools --> Logs? Any errors related to Plugwise-beta?

**Comment by sanderdw** [comment] 2020-05-18 10:19
![image](https://user-images.githubusercontent.com/19476345/82202190-d70a1280-9901-11ea-9d44-b36b446f246e.png)

**Comment by bouwew** [comment] 2020-05-18 10:24
Timeout fetching data means there is a not-so-great connection between the Smile and your Home Assistant server. For the rest it looks OK to me. Is it working now for you?

**Comment by sanderdw** [comment] 2020-05-18 11:29
No it's not working. The legacy (which i'm still using) is working fine though?

![image](https://user-images.githubusercontent.com/19476345/82208290-8d262a00-990b-11ea-8790-b01b14eb7d33.png)

**Comment by bouwew** [comment] 2020-05-18 11:46
Strange! Can you please also look at the sensors? Are these also not working?

**Comment by sanderdw** [comment] 2020-05-18 12:01
Also not working:
![image](https://user-images.githubusercontent.com/19476345/82210624-b21c9c00-990f-11ea-888f-63b52337c98b.png)

I'm testing on a seperate Pi3 with only the this new developed HACS version of the component.

My main HA instance is working correctly and there i still use the 'included Anna component'.

**Comment by bouwew** [comment] 2020-05-18 12:23
Ok, so you are running 2 Home Assistant instances in parallel? And your Smile is connected via Wifi?
It might be that your Smile is being overloaded due to maybe a not-so-good WiFi-connection.

@CoMPaTech anything to add?

**Comment by sanderdw** [comment] 2020-05-18 12:34
Yes correct. Smile is connected with LAN.

I will try to go back some versions to see if it's a programming error.

**Comment by sanderdw** [comment] 2020-05-18 12:45
Ok so looks like 0.2.4rc1 is running fine and from 0.2.7rc0 it's not working anymore.

**Comment by bouwew** [comment] 2020-05-18 12:49
Thanks, good feedback :)
I'll have a detailed look later today.

**Comment by bouwew** [comment] 2020-05-18 13:54
Can you please test plugwise-beta version 0.2.7rc0 with Smile versions 0.2.4, v0.2.5, v0.2.6 and v0.2.7?
Edit/modify the version number in plugwise-beta/manifest.json and then restart HA.

**Comment by bouwew** [comment] 2020-05-18 15:24
Also, on which HA version are you testing the new plugwise-beta versions?

**Comment by sanderdw** [comment] 2020-05-19 07:18
**Home Assistant 0.109.6**
plugwise-beta version 0.2.4rc1
v0.2.5 - Working

plugwise-beta version 0.2.7rc0
v0.2.4 - Not working
v0.2.5 - Not working
v0.2.6 - Not working
v0.2.7 - Not working

**Comment by bouwew** [comment] 2020-05-19 07:35
Thanks. Looks like the plugwise-beta-code could be the reason.
Are you still seeing the "timed out" errors in the log?

**Comment by sanderdw** [comment] 2020-05-19 08:18
Yes everything is connected with UTP only.

I remember i got timeout error's but didn't test this with an specific version. So if you want me to test this let me know.

**Comment by CoMPaTech** [comment] 2020-05-19 08:22
Lets diff versions

**Comment by CoMPaTech** [comment] 2020-05-19 08:36
(just ranting out loud) 
It sort of makes sense that they become unavailable - as per the upstream review we had to change to ConfigEntryNotReady (instead of PlatformNotReady) together with DUC (DataUpdateCoordinator) - so somewhere between these there is inconsistency w.r.t being available. But DUC combined with configentry not ready should trigger retries, so that's why I don't understand why they remain at unavailable. This is mostly 21e7e67

One thing I do see is that [here](https://github.com/plugwise/plugwise-beta/blob/2e5fdd4ac712d94d9a7b983742619de8e423ebed/custom_components/plugwise-beta/__init__.py#L13) we conformed to upstream not to have PNR in there in favour of CENR, but we still call PNR => if it hits timeouts or whatnot it shouldn't be working (since it doesn't know about PNR).

Back to ranting out loud - everything being unavailable reeks of DUC issues, I had those when trying to convert everything as well. Which would make sense, but your log clearly shows DUC is working as it shows 'Updating Smile thermostat (something:40 seconds) and as well calls [for updates](https://github.com/plugwise/plugwise-beta/blob/2e5fdd4ac712d94d9a7b983742619de8e423ebed/custom_components/plugwise-beta/sensor.py#L433).

@bouwew I think we should first replace the PNRs with ConfigEntryNotReady's and try again if @sanderdw is still willing and enthused - at the very least it should diverge so that just a config entry (that is, one of the entities) is acting up versus the whole platform.

**Comment by CoMPaTech** [comment] 2020-05-19 08:41
We could also add the 0.2.10 vs PR-63 for invalidauth in there, but that shouldn't be the issue. If the above rant sort of looks plausible lets at least see if #64 works better (i.e. shows what configentry is wrong instead of bugging the whole platform -> if I understand those workings correctly).

**Comment by bouwew** [comment] 2020-05-19 09:43
Yes, agree, lets try Smile 0.2.10 plus #64 first.

**Comment by CoMPaTech** [comment] 2020-05-19 10:24
Please see if/how `0.2.10b0` is doing

**Comment by bouwew** [comment] 2020-05-19 10:28
@sanderdw please remove the plugwise-beta integration from HA, then reboot HA, then install the new version via HACS and add the integration again.
Please follow this process to make sure nothing carries over from the old version.

**Comment by sanderdw** [comment] 2020-05-20 08:35
Unfortunately not working:
![image](https://user-images.githubusercontent.com/19476345/82424538-9e934180-9a85-11ea-82fe-54298500558e.png)

**Comment by bouwew** [comment] 2020-05-20 09:46
I'm getting more and more the idea that your Pi cannot connect to the Smile. Have you set up the networking on the Pi correctly? Can you open the Smile-website on a browser-windows on the Pi? Or can you ping the Smile IP successfully?

**Comment by sanderdw** [comment] 2020-05-20 10:08
But the same pi with 0.2.4rc1 is working fine? Also my second pi with the build-in Plugwise integration is also just working fine?

And yes i can connect with my browser:
![image](https://user-images.githubusercontent.com/19476345/82434021-95f53800-9a92-11ea-9be1-106806c836ee.png)

**Comment by bouwew** [comment] 2020-05-24 13:14
@sanderdw please try the latest version v0.2.11rc2 and let us know the result.

**Comment by sanderdw** [comment] 2020-05-25 13:21
Seems to work! I had to update to Home Assistant 0.110.2

![image](https://user-images.githubusercontent.com/19476345/82816352-48fed080-9e9b-11ea-9e3e-f6695f17ff9f.png)

![image](https://user-images.githubusercontent.com/19476345/82816374-55832900-9e9b-11ea-9e09-e2b347a11006.png)

**Comment by bouwew** [comment] 2020-05-25 13:32
Great news, thanks!

**Closed** 2020-05-26 07:08 UTC
Labels: bug, enhancement, invalid

**Comment by bouwew** [comment] 2021-01-31 11:59
@sanderdw We missen nog een stukje data/info van de legacy Anna. Zou jij eens kunnen kijken wat er staat op deze URLs?
http://<smile_ip>/system
http://<smile_ip>/system/status.xml

**Comment by sanderdw** [comment] 2021-02-01 09:32
Hi @bouwew, i don't use the Anna anymore. I switched to Tado because of independent zone control. So i'm adraid i can't help you guys anymore.
